/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
static yyconst short int yy_accept[289] =
    {   0,
        0,    0,   26,   24,    2,   19,   24,   24,   16,   19,
       24,   13,   16,   15,   16,   16,    7,    7,    7,    7,
       14,   20,   21,   20,    4,   19,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,   19,   24,   20,    0,   12,    9,    9,   18,    0,
       17,    0,    7,    7,    7,   23,   22,    5,    0,    9,
        9,    5,    7,    7,    7,    4,    4,    4,    4,    4,
        4,    4,    3,    4,    4,    4,    4,    4,    4,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    9,   10,    5,    7,    7,    7,   23,   22,    5,

        5,   11,    5,    7,    7,    7,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    9,    5,    7,
        7,    7,   11,    7,    7,    7,    4,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        9,    7,    7,    7,   11,    7,    7,    7,    4,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    9,    7,    7,    7,

       11,    7,    7,    7,    4,    4,    4,    3,    4,    4,
        4,    4,    4,    9,    7,    7,    7,   11,    7,    7,
        7,    4,    4,    3,    4,    4,    4,    4,    9,    7,
        7,    7,   11,    7,    7,    7,    4,    3,    9,    7,
        7,    7,    7,    7,    7,    4,    0,    0,    7,    7,
        7,    8,    8,    7,    4,    0,    8,    8,    8,    8,
        4,    0,    8,    8,    4,    0,    4,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    6,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,    7,   29,   30,
       31,   32,    7,    1,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        1,    1,    1,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   33,   45,   46,   47,   48,
       49,   50,   33,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    5,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    1,    7,    1,    3,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    1,
        1,    1
    } ;

static yyconst short int yy_base[356] =
    {   0,
        0,  448,  437, 1360, 1360,  384,  407,   57, 1360,  396,
        0, 1360,  377, 1360,   49,   53,   66,   96,  113,  366,
     1360,  345,  332,  328,   68, 1360,   71,   75,  121,  102,
       98,  104,  100,  141,  123,  152,  154,  156,  160,  162,
      169,  296,  171, 1360,  273,  228,   73,   89, 1360,  221,
     1360,  167,  174,  199,  187,    0,    0,  229,    0,  246,
      269,  292,  309,  319,  205,   91,  179,  181,   93,  189,
      193,  217,  223,  211,  231,  253,  233,  236,  255,  220,
      303,  273,  316,  277,  318,  344,  346,  298,  348,  355,
      358,  360, 1360,    0,  368,  372,  381,    0,    0,    0,

        0,    0,    0,  398,  408,  194,  238,  364,  375,  366,
      387,  390,  403,  377,  434,  438,  440,  442,  240,  444,
      446,  449,  451,  453,  455,  457,  459,  461,  463,  465,
      469,  475,  477,  480,  482,  491,  493,  496,    0,  506,
      511,  523,    0,  540,  550,  190,  294,  296,  498,  504,
      538,  525,  541,  529,  531,  544,  546,  548,  579,  582,
      584,  587,  589,  594,  596,  598,  600,  602,  604,  606,
      608,  610,  612,  632,    0,  649,  659,  176,  614,  616,
      644,  619,  653,  646,  655,  635,  657,  683,  690,  692,
      696,  698,  700,  702,  704,  706,  708,  710,  713,  719,

        0,  744,  754,  179,  715,  731,  733,  717,  749,  752,
      754,  777,  781,  785,  787,  790,  793,    0,  810,  820,
      165,  795,  812,  799,  802,  805,  843,  814,  849,  853,
      855,  858, 1360,  875,  885,  160,  807,  860,  911,  909,
      913,  915,  932,  942,  952,  862,  149,    0,  973,  975,
      977,  994, 1004,    0,  867,  148, 1027, 1029,    0,    0,
      870,  264, 1031, 1033,  872,  139,  874,  137,  878,  880,
      885,  917,  921,  927,  929,  933,  936,  939,  979,  981,
      989,  991,  993,  995,  997,  999, 1035, 1360, 1068, 1073,
     1080, 1084, 1088, 1093, 1098, 1102, 1106, 1112, 1119,  137,

     1124, 1129, 1133, 1137,  108, 1141, 1146, 1150,  106, 1154,
     1159, 1163,   78, 1167, 1172, 1176,   70, 1180, 1185, 1189,
       61, 1193, 1198, 1202, 1206, 1211, 1215, 1219, 1226, 1231,
     1235, 1239, 1244, 1248, 1252, 1257, 1262, 1267, 1272, 1277,
     1282, 1287, 1292, 1297, 1302, 1307, 1312, 1317, 1322, 1327,
     1332, 1337, 1342, 1347, 1352
    } ;

static yyconst short int yy_def[356] =
    {   0,
      288,    1,  288,  288,  288,  288,  289,  290,  288,  288,
      291,  288,  288,  288,  292,  288,  293,  293,   18,   19,
      288,  288,  288,  288,  294,  288,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  288,  290,  288,  289,  289,  290,  290,  288,  288,
      288,  295,  296,  297,  297,  298,  299,  290,  300,   19,
      293,   61,   19,   19,   64,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  290,  288,  302,  303,  304,  304,  298,  299,   58,

       58,  305,   62,   64,   64,  105,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  290,  302,  307,
      308,  308,  309,  105,  105,  145,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      290,  311,  312,  312,  313,  145,  145,  177,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  290,  315,  316,  316,

      317,  177,  177,  203,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  290,  319,  320,  320,  321,  203,  203,
      220,  322,  322,  322,  322,  322,  322,  322,  290,  323,
      324,  324,  288,  220,  220,  235,  325,  325,  290,  326,
      327,  327,  235,  235,  244,  328,  288,  329,  330,  331,
      331,  244,  244,  253,  332,  329,  333,  334,  252,  253,
      335,  329,  333,  334,  336,  329,  337,  329,  338,  339,
      340,  341,  342,  343,  344,  345,  346,  347,  348,  349,
      350,  351,  352,  353,  354,  355,  355,    0,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288
    } ;

static yyconst short int yy_nxt[1423] =
    {   0,
        4,    5,    4,    6,    7,    8,    8,    9,   10,   11,
       12,   12,    9,   13,   14,   15,    4,   16,   17,   18,
       19,   20,   20,   20,   20,   20,   20,   20,   21,   22,
       23,   24,   25,   26,   25,   27,   28,   29,   30,   31,
       32,   33,   25,   34,   25,   35,   25,   25,   25,   25,
       36,   37,   38,   39,   40,   41,   25,   25,   25,   12,
       42,   12,   47,   47,   51,   56,  233,   52,   53,   54,
       57,   58,   58,   47,   47,  218,   47,   47,   47,   47,
       47,   47,   59,  201,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   47,   47,   47,   47,   47,   47,

       62,   58,   58,   47,   47,   47,   47,   47,   47,   47,
       47,  175,   59,  143,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   67,   68,   47,   47,   47,   47,
       62,   64,   65,   64,   64,   64,   64,   64,   64,   64,
       64,   72,  102,   74,  110,   75,   47,   47,   79,   77,
       73,  247,   78,  262,   76,  262,   69,   47,   47,   47,
       47,   47,   47,   70,  262,   47,   47,   47,   47,   71,
      268,   82,   94,   94,   47,   47,   47,   47,  248,   94,
       94,   80,  245,   59,   47,   47,   47,   47,   81,  236,
       59,   83,   94,   94,   47,   47,   84,   85,   47,   47,

      221,   94,  204,   59,   94,   94,   86,   89,   94,   87,
       90,   91,  178,   88,   92,   59,   47,   47,   97,  146,
      109,   94,   47,   47,  111,   47,   47,  106,   47,   47,
       93,  108,   46,   94,  100,  100,   47,   47,   47,   47,
      112,   47,   47,   47,   47,   47,   47,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  113,   47,   47,
       47,   47,  115,  101,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   47,   47,  114,   46,   47,   47,
      262,  118,   47,   47,  116,  288,  119,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,  100,  100,   47,

       47,   47,   47,   47,   47,  117,  266,  120,   47,   47,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      122,   47,   47,   47,   47,  126,  103,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  132,  121,   47,
       47,   47,   47,   47,   47,  119,   49,  123,   44,  127,
       47,   47,   44,   47,   47,   47,   47,  124,  125,   47,
       47,   47,   47,   94,   94,   44,  128,   94,   94,  129,
       47,   47,   47,   47,   59,   64,   94,   94,   59,  131,
       51,  133,   47,   47,  130,   47,   47,   59,  135,  134,

      136,  137,   94,  142,   49,  148,   94,  138,   47,   47,
      149,   46,  148,  153,   44,   94,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  288,  148,  152,   47,
       47,  150,  151,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   43,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,  288,  148,   47,   47,  288,  155,  288,  154,
       47,   47,   47,   47,  148,   47,   47,   47,   47,  156,
      148,  288,  148,  288,  157,  288,   47,   47,   47,   47,

      162,   47,   47,   47,   47,  158,  161,  160,  159,   47,
       47,   94,   94,  288,  166,  163,   94,   94,  164,  288,
      148,  165,   59,  168,  288,  167,  169,   59,   94,   94,
       47,   47,  288,  171,   47,   47,   47,   47,  170,   59,
       94,  288,  180,   47,   47,   94,   47,   47,  174,   47,
       47,   47,   47,   47,   47,  288,  180,   94,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  182,  184,
      288,  181,  288,  180,   47,   47,  183,   47,   47,   47,
       47,  185,   47,   47,   47,   47,  288,  186,  187,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   94,   94,   94,   94,   47,
       47,   47,   47,  189,   47,   47,   59,  288,   59,  188,
      288,  192,  191,  193,  180,  190,  194,   94,   94,  288,
       47,   47,  288,  195,   94,  180,   94,  180,   59,   47,
       47,   47,   47,  197,  200,  288,  196,  288,   47,   47,
       47,   47,   47,   47,  207,  288,   94,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  209,   47,   47,
      288,  206,  208,  208,  208,   47,   47,   47,   47,  288,

      210,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   94,   94,  288,   94,   94,
       47,   47,   47,   47,   94,   94,   59,  288,  208,   59,
      208,  288,  208,  208,  288,   59,   47,   47,   47,   47,
      288,  211,  208,  288,   94,  217,  288,   94,  288,  213,
      208,  212,  288,   94,   47,   47,  288,   47,   47,   47,
       47,  214,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  219,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,   47,   47,  223,  224,   47,   47,  225,  226,
       47,   47,   94,   94,  224,   94,   94,  288,   94,   94,

       47,   47,  288,   59,   47,   47,   59,   47,   47,   59,
       47,   47,   47,   47,  232,  288,  227,   47,   47,   47,
       47,   94,  288,  229,   94,  288,  228,   94,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,   47,   47,
      288,  238,  238,  238,   47,   47,  288,  238,   94,   94,
       94,   94,  288,   94,   94,   47,   47,   47,   47,   59,
      288,   59,   47,   47,   59,   47,   47,   47,   47,   47,
       47,  238,  242,   47,   47,   47,   47,   94,  239,   94,
       47,   47,   94,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  247,   94,   94,   47,   47,   94,   94,
       94,   94,   47,   47,  288,   59,   47,   47,  288,   59,
      288,   59,   47,   47,   47,   47,  288,  251,   47,   47,
      248,   47,   47,   94,   47,   47,  288,   94,  288,   94,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  254,  254,  254,  254,  254,  254,  254,   94,   94,
       94,   94,   94,   94,   47,   47,   47,   47,  288,   59,
      288,   59,  288,   59,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,  288,   94,  288,   94,
      288,   94,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,   94,   94,   94,   94,   94,   94,   94,   94,
       47,   47,  288,   59,  288,   59,  288,   59,  288,   59,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,   94,  288,   94,  288,   94,  288,   94,   45,  288,
       45,   45,   45,   45,   45,   48,  288,  288,   48,   48,
       50,  288,   50,   50,   50,   50,   50,   55,  288,   55,
       61,  288,   61,   61,   61,   66,  288,  288,   66,   66,

       52,  288,   52,   52,   95,  288,   95,   95,   96,  288,
       96,   96,   98,   98,   98,   98,   98,   98,   98,   99,
      288,   99,   99,   99,   99,   99,  107,  288,  288,  107,
      107,  139,  288,  288,  139,  140,  288,  140,  140,  141,
      288,  141,  141,  147,  288,  288,  147,  147,  172,  288,
      172,  172,  173,  288,  173,  173,  179,  288,  288,  179,
      179,  198,  288,  198,  198,  199,  288,  199,  199,  205,
      288,  288,  205,  205,  215,  288,  215,  215,  216,  288,
      216,  216,  222,  288,  288,  222,  222,  230,  288,  230,
      230,  231,  288,  231,  231,  237,  288,  288,  237,  237,

      240,  288,  240,  240,  241,  288,  241,  241,  246,  288,
      288,  246,  246,  249,  288,  249,  249,  250,  288,  250,
      250,  255,  288,  288,  255,  255,  256,  288,  256,  256,
      256,  256,  256,  257,  288,  257,  257,  258,  288,  258,
      258,  261,  288,  288,  261,  261,  263,  288,  263,  263,
      264,  288,  264,  264,  265,  288,  288,  265,  265,  267,
      288,  288,  267,  267,  269,  288,  288,  269,  269,  270,
      288,  288,  270,  270,  271,  288,  288,  271,  271,  272,
      288,  288,  272,  272,  273,  288,  288,  273,  273,  274,
      288,  288,  274,  274,  275,  288,  288,  275,  275,  276,

      288,  288,  276,  276,  277,  288,  288,  277,  277,  278,
      288,  288,  278,  278,  279,  288,  288,  279,  279,  280,
      288,  288,  280,  280,  281,  288,  288,  281,  281,  282,
      288,  288,  282,  282,  283,  288,  288,  283,  283,  284,
      288,  288,  284,  284,  285,  288,  288,  285,  285,  286,
      288,  288,  286,  286,  287,  288,  288,  287,  287,    3,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288
    } ;

static yyconst short int yy_chk[1423] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    8,   15,   16,  321,   15,   15,   15,
       16,   17,   17,   25,   25,  317,   27,   27,   47,   47,
       28,   28,   17,  313,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   48,   48,   66,   66,   69,   69,

       17,   18,   18,   31,   31,   33,   33,   30,   30,   32,
       32,  309,   18,  305,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   27,   28,   29,   29,   35,   35,
       18,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   30,  300,   31,   69,   31,   34,   34,   33,   32,
       30,  247,   32,  268,   31,  266,   29,   36,   36,   37,
       37,   38,   38,   29,  256,   39,   39,   40,   40,   29,
      266,   35,   52,   52,   41,   41,   43,   43,  247,   53,
       53,   34,  236,   52,   67,   67,   68,   68,   34,  221,
       53,   36,   55,   55,   70,   70,   37,   37,   71,   71,

      204,   52,  178,   55,   54,   54,   37,   39,   53,   37,
       40,   41,  146,   38,   43,   54,   74,   74,   54,  106,
       68,   55,   72,   72,   70,   80,   80,   65,   73,   73,
       50,   67,   46,   54,   58,   58,   75,   75,   77,   77,
       71,   78,   78,  107,  107,  119,  119,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   72,   76,   76,
       79,   79,   74,   58,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   61,   61,   73,   45,   82,   82,
      262,   77,   84,   84,   75,   61,   78,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   62,   62,  147,

      147,  148,  148,   88,   88,   76,  262,   79,   81,   81,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       82,   83,   83,   85,   85,   84,   62,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   88,   81,   86,
       86,   87,   87,   89,   89,   81,   42,   83,   24,   85,
       90,   90,   23,   91,   91,   92,   92,   83,   83,  108,
      108,  110,  110,   95,   95,   22,   85,   96,   96,   86,
      109,  109,  114,  114,   95,   20,   97,   97,   96,   87,
       13,   89,  111,  111,   86,  112,  112,   97,   90,   89,

       90,   91,   95,   97,   10,  110,   96,   92,  113,  113,
      109,    7,  108,  114,    6,   97,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,    3,  111,  113,  115,
      115,  112,  112,  116,  116,  117,  117,  118,  118,  120,
      120,  121,  121,    2,  122,  122,  123,  123,  124,  124,
      125,  125,  126,  126,  127,  127,  128,  128,  129,  129,
      130,  130,    0,  115,  131,  131,    0,  118,    0,  117,
      132,  132,  133,  133,  116,  134,  134,  135,  135,  121,
      122,    0,  120,    0,  123,    0,  136,  136,  137,  137,

      128,  138,  138,  149,  149,  124,  127,  126,  125,  150,
      150,  140,  140,    0,  132,  129,  141,  141,  130,    0,
      135,  131,  140,  134,    0,  133,  136,  141,  142,  142,
      152,  152,    0,  138,  154,  154,  155,  155,  137,  142,
      140,    0,  149,  151,  151,  141,  153,  153,  142,  156,
      156,  157,  157,  158,  158,    0,  150,  142,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  152,  154,
        0,  151,    0,  155,  159,  159,  153,  160,  160,  161,
      161,  156,  162,  162,  163,  163,    0,  157,  158,  164,

      164,  165,  165,  166,  166,  167,  167,  168,  168,  169,
      169,  170,  170,  171,  171,  172,  172,  173,  173,  179,
      179,  180,  180,  161,  182,  182,  172,    0,  173,  159,
        0,  164,  163,  165,  160,  162,  166,  174,  174,    0,
      186,  186,    0,  168,  172,  170,  173,  167,  174,  181,
      181,  184,  184,  171,  174,    0,  169,    0,  183,  183,
      185,  185,  187,  187,  182,    0,  174,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  186,  188,  188,
        0,  181,  183,  184,  185,  189,  189,  190,  190,    0,

      187,  191,  191,  192,  192,  193,  193,  194,  194,  195,
      195,  196,  196,  197,  197,  198,  198,    0,  199,  199,
      205,  205,  208,  208,  200,  200,  198,    0,  189,  199,
      188,    0,  190,  191,    0,  200,  206,  206,  207,  207,
        0,  194,  193,    0,  198,  200,    0,  199,    0,  196,
      192,  195,    0,  200,  209,  209,    0,  210,  210,  211,
      211,  197,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  212,  212,  206,  207,  213,  213,  209,  210,
      214,  214,  215,  215,  211,  216,  216,    0,  217,  217,

      222,  222,    0,  215,  224,  224,  216,  225,  225,  217,
      226,  226,  237,  237,  217,    0,  212,  223,  223,  228,
      228,  215,    0,  214,  216,    0,  213,  217,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  227,  227,
        0,  223,  225,  228,  229,  229,    0,  226,  230,  230,
      231,  231,    0,  232,  232,  238,  238,  246,  246,  230,
        0,  231,  255,  255,  232,  261,  261,  265,  265,  267,
      267,  227,  232,  269,  269,  270,  270,  230,  229,  231,
      271,  271,  232,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  239,  240,  240,  239,  239,  241,  241,
      242,  242,  272,  272,    0,  240,  273,  273,    0,  241,
        0,  242,  274,  274,  275,  275,    0,  242,  276,  276,
      239,  277,  277,  240,  278,  278,    0,  241,    0,  242,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      245,  245,  245,  245,  245,  245,  245,  245,  249,  249,
      250,  250,  251,  251,  279,  279,  280,  280,    0,  249,
        0,  250,    0,  251,  281,  281,  282,  282,  283,  283,

      284,  284,  285,  285,  286,  286,    0,  249,    0,  250,
        0,  251,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  257,  257,  258,  258,  263,  263,  264,  264,
      287,  287,    0,  257,    0,  258,    0,  263,    0,  264,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  257,    0,  258,    0,  263,    0,  264,  289,    0,
      289,  289,  289,  289,  289,  290,    0,    0,  290,  290,
      291,    0,  291,  291,  291,  291,  291,  292,    0,  292,
      293,    0,  293,  293,  293,  294,    0,    0,  294,  294,

      295,    0,  295,  295,  296,    0,  296,  296,  297,    0,
      297,  297,  298,  298,  298,  298,  298,  298,  298,  299,
        0,  299,  299,  299,  299,  299,  301,    0,    0,  301,
      301,  302,    0,    0,  302,  303,    0,  303,  303,  304,
        0,  304,  304,  306,    0,    0,  306,  306,  307,    0,
      307,  307,  308,    0,  308,  308,  310,    0,    0,  310,
      310,  311,    0,  311,  311,  312,    0,  312,  312,  314,
        0,    0,  314,  314,  315,    0,  315,  315,  316,    0,
      316,  316,  318,    0,    0,  318,  318,  319,    0,  319,
      319,  320,    0,  320,  320,  322,    0,    0,  322,  322,

      323,    0,  323,  323,  324,    0,  324,  324,  325,    0,
        0,  325,  325,  326,    0,  326,  326,  327,    0,  327,
      327,  328,    0,    0,  328,  328,  329,    0,  329,  329,
      329,  329,  329,  330,    0,  330,  330,  331,    0,  331,
      331,  332,    0,    0,  332,  332,  333,    0,  333,  333,
      334,    0,  334,  334,  335,    0,    0,  335,  335,  336,
        0,    0,  336,  336,  337,    0,    0,  337,  337,  338,
        0,    0,  338,  338,  339,    0,    0,  339,  339,  340,
        0,    0,  340,  340,  341,    0,    0,  341,  341,  342,
        0,    0,  342,  342,  343,    0,    0,  343,  343,  344,

        0,    0,  344,  344,  345,    0,    0,  345,  345,  346,
        0,    0,  346,  346,  347,    0,    0,  347,  347,  348,
        0,    0,  348,  348,  349,    0,    0,  349,  349,  350,
        0,    0,  350,  350,  351,    0,    0,  351,  351,  352,
        0,    0,  352,  352,  353,    0,    0,  353,  353,  354,
        0,    0,  354,  354,  355,    0,    0,  355,  355,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lexicalAnalyser.l"
#define INITIAL 0
#line 2 ".\\lexicalAnalyser.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define TABLE_SIZE 100003
#define MAX_SYMBOLS 1000000

int line_num = 1;

char * locations[MAX_SYMBOLS];
int symTableSize=0;

struct lines{
    int lineno; // stores the line-number
    struct lines*next;
};
struct SymbolTableEntry {
    char * name; //identifier
    char * type;
    int size;
    struct SymbolTableEntry * next;
    struct lines * head; //head of the linenumbers list
    struct lines *  tail; //tail of the linenumbers list
};

struct SymbolTable {
    struct SymbolTableEntry * symTable[TABLE_SIZE];
};

struct SymbolTable Table;

//Hash Function
int hashfunction(char *s) {
    int pp = 101;
    int mod = TABLE_SIZE;
    int val = 0;
    int n = strlen(s);
    int p = 1;
    for (int i = 0; i < n; i++) {
        int c = s[i];
        val = (val + ((c * p) % mod)) % mod;
        p = (p * pp) % mod;
    }
    return val;
}

// Function to insert a key-value pair (doesnt exist) into the SymbolTable 
void insert1(char* key,char * type,int linenumber) {
    int index = hashfunction(key);

    // Create a new entry
    struct SymbolTableEntry* new_entry = (struct SymbolTableEntry*)malloc(sizeof(struct SymbolTableEntry));

    new_entry->name = strdup(key); // Duplicate the key string
    new_entry->type = strdup(type); // Duplicate the type string
    new_entry->size = strlen(key); 
    new_entry->next = Table.symTable[index];
    new_entry->head = (struct lines *)malloc(sizeof(struct lines));
    new_entry->head->lineno = linenumber;
    new_entry->head->next = NULL;
    new_entry->tail = new_entry->head;
    Table.symTable[index] = new_entry;
    locations[symTableSize++]=strdup(key);
}

//Function to append an entry for key-value pair that already exists in the SymbolTable
void insert2(struct SymbolTableEntry* entry,int linenumber){
    struct lines * new_node = (struct lines *)malloc(sizeof(struct lines));
    new_node->lineno = linenumber;
    new_node->next = NULL;
    entry->tail->next = new_node;
    entry->tail = new_node;
}

// Function to Lookup
struct SymbolTableEntry *  lookup(char* key) {
    int index = hashfunction(key);
    struct SymbolTableEntry* entry = Table.symTable[index];
    while(entry != NULL)
        {
            if(strcmp(entry->name,key) == 0)
            {
                return entry;
            } 
            entry = entry->next;
        }
        // Key not found
        return NULL;
}

void processToken(const char* token,char *category,int linenumber) {
    char* buffer = (char*)malloc(strlen(token) + 1);
    strcpy(buffer, token);
    //printf("%s : %s\n", category, buffer);
    struct SymbolTableEntry* found = lookup(buffer);
    if (found == NULL) {
        insert1(buffer, category,linenumber);
    }
    else{
        insert2(found,linenumber);
    }
    free(buffer);
}

#line 891 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 107 ".\\lexicalAnalyser.l"

#line 1047 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 289 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1360 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tHEADER FILE \t%20d\n", yytext,line_num);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 ".\\lexicalAnalyser.l"
{line_num++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 112 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tKEYWORD \t%24d\n", yytext,line_num);};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 114 ".\\lexicalAnalyser.l"
{
    processToken(yytext, "Identifier", line_num);
    fprintf(yyout, "%30s \t--->\tIDENTIFIER \t%22d\n", yytext, line_num);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 ".\\lexicalAnalyser.l"
{
   printf("\n\nERROR : Constant '%s' is invalid\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Identifier '%s' is too long\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 127 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"Integer Constants",line_num);
    fprintf(yyout,"%30s \t--->\tINTERGER CONSTANT \t%14d\n", yytext,line_num);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Integer Limit Exceed\nline no : %d",line_num);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Identifier '%s' is invalid\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 ".\\lexicalAnalyser.l"
{
    fprintf(yyout,"%30s \t--->\tCHARACTER CONSTANT \t%13d\n", yytext,line_num);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"Floating-Point Constants",line_num);
    fprintf(yyout,"%30s \t--->\tFLOATING-POINT CONSTANT \t%30d\n", yytext,line_num);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 149 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"String Literal",line_num);
    fprintf(yyout,"%30s \t--->\tSTRING LITERAL \t%18d\n", yytext,line_num);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 154 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tPARENTHESIS \t%20d\n", yytext,line_num+1);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tSEMICOLON \t%22d\n", yytext,line_num+1);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 158 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tCOMMA \t%28d\n", yytext,line_num+1);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 160 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tARITHMETIC OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 162 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tUNARY OPERATOR \t%18d\n", yytext,line_num+1);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tLOGICAL OPERATOR \t%16d\n", yytext,line_num+1);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 166 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tBIT-WISE OPERATOR \t%14d\n", yytext,line_num+1);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 168 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tRELATIONAL OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 170 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tASSIGNMENT OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 172 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tSINGLELINE COMMENT \t%14d\n",yytext,line_num+1);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 ".\\lexicalAnalyser.l"
{printf("\n\nERROR : Invalid Comment '%s' \nline no : %d", yytext, line_num);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 176 ".\\lexicalAnalyser.l"
;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 178 ".\\lexicalAnalyser.l"
ECHO;
	YY_BREAK
#line 1278 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 289 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 289 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 288);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 178 ".\\lexicalAnalyser.l"


int yywrap(){
    return 1;
}

int main(){
    for (int i=0; i<TABLE_SIZE;i++) {
        Table.symTable[i] = NULL;
    }
    yyin = fopen("input.txt","r");
    yyout=fopen("ListOfTokens.txt","w");
    fprintf(yyout,"\n-------------------------------------------------------------------------------------------------------\n");
    fprintf(yyout,"%30s \t--->\t %s \t%30s", "Lexeme", "Token","Line Number");
    fprintf(yyout,"\n-------------------------------------------------------------------------------------------------------\n");
    yylex();
    printf("\n\nSYMBOL TABLE\n\n");
    printf("%-15s  %-10s  %-20s  %-20s\n", "Identifier", "Size", "Type", "Line Numbers");
    printf("---------------------------------------------------------------\n");

    for (int i = 0; i < symTableSize; i++) {
        struct SymbolTableEntry * entry = lookup(locations[i]);
        printf("%-15s  %-10d  %-20s  [ ", entry->name, entry->size, entry->type);
        struct lines* h = entry->head;
        while(h){
            printf("%d ", h->lineno);
            h = h->next;
        }
        printf("]\n");
    }
    printf("---------------------------------------------------------------\n");
    printf("\n\n");
    fclose(yyin);
    return 0;
}