/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
static yyconst short int yy_accept[293] =
    {   0,
        0,    0,   28,   26,    2,   19,   25,   26,   16,   19,
       26,   13,   16,   16,   15,   16,   16,    7,    7,    7,
        7,   14,   20,   21,   20,    4,   19,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,   19,   26,   20,   25,   25,   12,    9,    9,
       18,    0,   23,   17,    0,    7,    7,    7,   24,   22,
        5,    0,    9,    9,    5,    7,    7,    7,    4,    4,
        4,    4,    4,    4,    4,    3,    4,    4,    4,    4,
        4,    4,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    9,    0,   10,    5,    7,    7,

        7,   24,   22,    5,    5,   11,    5,    7,    7,    7,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    9,    5,    7,    7,    7,   11,    7,    7,    7,
        4,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    9,    7,    7,    7,   11,    7,
        7,    7,    4,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        9,    7,    7,    7,   11,    7,    7,    7,    4,    4,
        4,    3,    4,    4,    4,    4,    4,    9,    7,    7,
        7,   11,    7,    7,    7,    4,    4,    3,    4,    4,
        4,    4,    9,    7,    7,    7,   11,    7,    7,    7,
        4,    3,    9,    7,    7,    7,    7,    7,    7,    4,
        0,    0,    7,    7,    7,    8,    8,    7,    4,    0,
        8,    8,    8,    8,    4,    0,    8,    8,    4,    0,
        4,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        6,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,    7,   29,   30,
       31,   32,    7,    1,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        1,    1,    1,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   33,   45,   46,   47,   48,
       49,   50,   33,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    1,    1,    3,    4,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    1,    8,    1,    4,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        1,    1
    } ;

static yyconst short int yy_base[362] =
    {   0,
        0,  387,  391, 1392, 1392,  358,   61,   58, 1392,  376,
        0, 1392,  362,  363, 1392,   51,   55,   68,   98,  115,
      349, 1392,  333,  331,  281,   70, 1392,   73,   77,  123,
      104,  100,  106,  102,  143,  125,  154,  156,  158,  162,
      164,  171,  249,  173, 1392,   76,    0,  303,   91,   93,
     1392,  269, 1392, 1392,  169,  176,  201,  189,    0,    0,
      231,    0,  248,  271,  294,  311,  321,  212,   95,  181,
      183,  191,  195,  213,  219,  226,  233,  235,  256,  238,
      275,  258,  221,  317,  277,  344,  346,  348,  321,  242,
      352,  354,  359,  367,  361,  217, 1392,    0,  375,  377,

      407,    0,    0,    0,    0,    0,    0,  424,  434,  189,
      223,  369,  372,  381,  413,  416,  393,  426,  430,  419,
      432,  467,  240,  428,  421,  434,  472,  474,  476,  478,
      480,  482,  484,  486,  488,  491,  493,  495,  499,  507,
      501,  511,    0,  517,  519,  538,    0,  555,  565,  182,
      296,  298,  503,  505,  513,  544,  526,  553,  555,  559,
      561,  563,  588,  590,  593,  595,  603,  599,  610,  612,
      605,  614,  616,  618,  620,  624,  628,  648,    0,  665,
      675,  176,  300,  409,  622,  661,  666,  668,  670,  655,
      673,  675,  698,  705,  707,  712,  714,  718,  720,  722,

      724,  643,  726,  732,    0,  760,  770,  170,  728,  745,
      747,  734,  763,  766,  768,  770,  756,  799,  801,  805,
      807,    0,  824,  834,  160,  741,  824,  749,  814,  810,
      827,  861,  863,  865,  867,  869, 1392,  886,  896,  144,
      819,  821,  922,  920,  924,  926,  943,  953,  963,  871,
      151,    0,  984,  986,  988, 1005, 1015,    0,  873,  141,
     1038, 1040,    0,    0,  881,  130, 1042, 1044,  883,  339,
      885,  139,  889,  891,  928,  932,  938,  940,  944,  947,
      950,  990,  992, 1000, 1002, 1004, 1006, 1008, 1010, 1046,
     1056, 1392, 1079, 1084, 1092, 1096, 1100, 1105, 1113, 1121,

     1126, 1130, 1134, 1141, 1149,  138, 1154, 1159, 1163, 1167,
      109, 1171, 1176, 1180,  107, 1184, 1189, 1193,   79, 1197,
     1202, 1206,   75, 1210, 1215, 1219,   62, 1223, 1228, 1232,
     1236, 1241, 1245, 1249, 1257, 1262, 1266, 1270, 1275, 1279,
     1283, 1288, 1293, 1298, 1303, 1308, 1313, 1318, 1323, 1328,
     1333, 1338, 1343, 1348, 1353, 1358, 1363, 1368, 1373, 1378,
     1383
    } ;

static yyconst short int yy_def[362] =
    {   0,
      292,    1,  292,  292,  292,  292,  293,  294,  292,  292,
      295,  292,  292,  292,  292,  296,  292,  297,  297,   19,
       20,  292,  292,  292,  292,  298,  292,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  292,  294,  292,  293,  299,  300,  294,  294,
      292,  292,  292,  292,  301,  302,  303,  303,  304,  305,
      294,  306,   20,  297,   64,   20,   20,   67,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  294,  300,  292,  308,  309,  310,

      310,  304,  305,   61,   61,  311,   65,   67,   67,  109,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  294,  308,  313,  314,  314,  315,  109,  109,  149,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  294,  317,  318,  318,  319,  149,
      149,  181,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      294,  321,  322,  322,  323,  181,  181,  207,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  294,  325,  326,
      326,  327,  207,  207,  224,  328,  328,  328,  328,  328,
      328,  328,  294,  329,  330,  330,  292,  224,  224,  239,
      331,  331,  294,  332,  333,  333,  239,  239,  248,  334,
      292,  335,  336,  337,  337,  248,  248,  257,  338,  335,
      339,  340,  256,  257,  341,  335,  339,  340,  342,  335,
      343,  335,  344,  345,  346,  347,  348,  349,  350,  351,
      352,  353,  354,  355,  356,  357,  358,  359,  360,  361,
      361,    0,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292
    } ;

static yyconst short int yy_nxt[1455] =
    {   0,
        4,    5,    4,    6,    7,    8,    8,    9,   10,   11,
       12,   12,   13,   14,   15,   16,    4,   17,   18,   19,
       20,   21,   21,   21,   21,   21,   21,   21,   22,   23,
       24,   25,   26,   27,   26,   28,   29,   30,   31,   32,
       33,   34,   26,   35,   26,   36,   26,   26,   26,   26,
       37,   38,   39,   40,   41,   42,   26,   26,   26,   12,
       43,   12,   47,   49,   49,   48,   54,   59,  237,   55,
       56,   57,   60,   61,   61,   49,   49,   47,   49,   49,
       48,  222,   49,   49,   62,  205,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   49,   49,   49,   49,

       49,   49,   65,   61,   61,   49,   49,   49,   49,   49,
       49,   49,   49,  179,   62,  147,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   70,   71,   49,   49,
       49,   49,   65,   67,   68,   67,   67,   67,   67,   67,
       67,   67,   67,   75,  106,   77,  266,   78,   49,   49,
       82,   80,   76,  251,   81,  266,   79,  266,   72,   49,
       49,   49,   49,   49,   49,   73,  249,   49,   49,   49,
       49,   74,  270,   85,   98,   98,   49,   49,   49,   49,
      252,   98,   98,   83,  240,   62,   49,   49,   49,   49,
       84,  225,   62,   86,   98,   98,   49,   49,   87,   88,

       49,   49,  208,   98,  182,   62,   98,   98,   89,   92,
       98,   90,   93,   94,  150,   91,   95,   62,   49,   49,
      101,   48,  113,   98,   49,   49,   49,   49,   49,   49,
      115,   49,   49,  112,  110,   98,  104,  104,   49,   49,
       49,   49,  114,   49,   49,   49,   49,   49,   49,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  117,
      116,   49,   49,   49,   49,  105,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   49,   49,   97,  118,
       49,   49,   49,   49,  119,  135,  122,  292,  120,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,  104,

      104,   49,   49,   49,   49,   49,   49,   48,  121,   51,
      124,   45,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,   49,   49,  126,  123,   49,   49,  107,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,   49,
       49,   49,   49,   49,   49,  266,  133,   49,   49,   49,
       49,   45,  125,   45,   49,   49,   49,   49,   67,  123,
      272,  134,   49,   49,   49,   49,   54,   49,   49,   53,
       98,   98,   98,   98,   51,  127,   49,   49,   45,  131,
      292,   62,   44,   62,  130,  128,  129,  137,   49,   49,

      292,  136,  139,  292,  140,  138,  132,  153,  142,   98,
      141,   98,   98,   98,   49,   49,  292,  152,   49,   49,
      152,   49,   49,   62,   49,   49,   49,   49,  156,  146,
      292,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   98,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  157,  152,  160,  152,  292,  154,  155,  152,
      292,  158,   49,   49,  292,  152,  152,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,  292,   49,   49,   49,   49,

       49,   49,  159,  292,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,  292,  161,   49,   49,   49,   49,
      292,  166,   98,   98,   98,   98,  162,  165,  164,  163,
      170,   49,   49,   62,  292,   62,  167,  152,  172,  168,
      169,  171,  173,   98,   98,  292,  174,  184,  175,   49,
       49,   98,  292,   98,   62,  292,  185,  184,   49,   49,
       49,   49,  292,  178,   49,   49,   49,   49,   49,   49,
      292,  187,   98,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,   49,   49,   49,   49,  186,   49,   49,

       49,   49,  292,  188,   49,   49,  189,  184,   49,   49,
       49,   49,  190,  191,  292,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   98,
       98,  292,  193,   98,   98,  292,  196,  292,  192,  292,
       62,  292,  184,  194,   62,  292,  195,  197,   98,   98,
      198,  292,  184,   98,   98,  199,  292,  184,   98,   62,
       49,   49,   98,  292,   62,  201,   49,   49,  200,  210,
      204,   49,   49,   49,   49,   49,   49,   98,   49,   49,
       49,   49,   98,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,   49,   49,  212,  211,  213,  292,  212,
       49,   49,   49,   49,  292,  212,  214,   49,   49,   49,
       49,  292,  212,   49,   49,   49,   49,   49,   49,   49,
       49,   98,   98,   49,   49,  292,  212,   98,   98,   49,
       49,  292,   62,  292,  212,  212,   49,   49,   62,  292,
       49,   49,   49,   49,   49,   49,  212,  215,  221,  292,
       98,   49,   49,  292,  212,  217,   98,  216,   49,   49,
      292,   49,   49,   49,   49,   49,   49,  218,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  227,  228,

      292,  232,  229,  230,   49,   49,   98,   98,  228,  231,
       98,   98,   98,   98,  292,   49,   49,   62,  292,   49,
       49,   62,  292,   62,   49,   49,   49,   49,  236,   49,
       49,  292,   49,   49,  292,   98,  292,  233,  292,   98,
      292,   98,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  242,  242,  242,  242,   49,   49,   49,   49,
       98,   98,   98,   98,   98,   98,   49,   49,   49,   49,
      292,   62,  292,   62,  292,   62,   49,   49,   49,   49,
       49,   49,  292,  246,   49,   49,   49,   49,  292,   98,

      242,   98,  243,   98,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  251,   98,   98,   49,   49,   98,
       98,   98,   98,   49,   49,  292,   62,   49,   49,  292,
       62,  292,   62,   49,   49,   49,   49,  292,  255,   49,
       49,  252,   49,   49,   98,   49,   49,  292,   98,  292,
       98,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  258,  258,  258,  258,  258,  258,  258,  258,   98,
       98,   98,   98,   98,   98,   49,   49,   49,   49,  292,

       62,  292,   62,  292,   62,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,  292,   98,  292,
       98,  292,   98,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,   98,   98,   98,   98,   98,   98,   98,
       98,   49,   49,  292,   62,  292,   62,  292,   62,  292,
       62,   49,   49,  292,  292,  292,  292,  292,  292,  292,
      292,  292,   98,  292,   98,  292,   98,  292,   98,   46,
       46,   46,   46,   46,   46,   46,   46,   50,  292,  292,
       50,   50,   52,  292,   52,   52,   52,   52,   52,   52,

       58,  292,   58,   64,  292,   64,   64,   64,   69,  292,
      292,   69,   69,   47,   47,  292,   47,   47,   47,   47,
       47,   96,  292,   96,   96,   96,   96,   96,   96,   55,
      292,   55,   55,   99,  292,   99,   99,  100,  292,  100,
      100,  102,  102,  102,  102,  102,  102,  102,  102,  103,
      292,  103,  103,  103,  103,  103,  103,  111,  292,  292,
      111,  111,  143,  292,  292,  143,  144,  292,  144,  144,
      145,  292,  145,  145,  151,  292,  292,  151,  151,  176,
      292,  176,  176,  177,  292,  177,  177,  183,  292,  292,
      183,  183,  202,  292,  202,  202,  203,  292,  203,  203,

      209,  292,  292,  209,  209,  219,  292,  219,  219,  220,
      292,  220,  220,  226,  292,  292,  226,  226,  234,  292,
      234,  234,  235,  292,  235,  235,  241,  292,  292,  241,
      241,  244,  292,  244,  244,  245,  292,  245,  245,  250,
      292,  292,  250,  250,  253,  292,  253,  253,  254,  292,
      254,  254,  259,  292,  292,  259,  259,  260,  292,  260,
      260,  260,  260,  260,  260,  261,  292,  261,  261,  262,
      292,  262,  262,  265,  292,  292,  265,  265,  267,  292,
      267,  267,  268,  292,  268,  268,  269,  292,  292,  269,
      269,  271,  292,  292,  271,  271,  273,  292,  292,  273,

      273,  274,  292,  292,  274,  274,  275,  292,  292,  275,
      275,  276,  292,  292,  276,  276,  277,  292,  292,  277,
      277,  278,  292,  292,  278,  278,  279,  292,  292,  279,
      279,  280,  292,  292,  280,  280,  281,  292,  292,  281,
      281,  282,  292,  292,  282,  282,  283,  292,  292,  283,
      283,  284,  292,  292,  284,  284,  285,  292,  292,  285,
      285,  286,  292,  292,  286,  286,  287,  292,  292,  287,
      287,  288,  292,  292,  288,  288,  289,  292,  292,  289,
      289,  290,  292,  292,  290,  290,  291,  292,  292,  291,
      291,    3,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292
    } ;

static yyconst short int yy_chk[1455] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    8,    8,    7,   16,   17,  327,   16,
       16,   16,   17,   18,   18,   26,   26,   46,   28,   28,
       46,  323,   29,   29,   18,  319,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   49,   49,   50,   50,

       69,   69,   18,   19,   19,   32,   32,   34,   34,   31,
       31,   33,   33,  315,   19,  311,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   28,   29,   30,   30,
       36,   36,   19,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   31,  306,   32,  266,   32,   35,   35,
       34,   33,   31,  251,   33,  272,   32,  260,   30,   37,
       37,   38,   38,   39,   39,   30,  240,   40,   40,   41,
       41,   30,  266,   36,   55,   55,   42,   42,   44,   44,
      251,   56,   56,   35,  225,   55,   70,   70,   71,   71,
       35,  208,   56,   37,   58,   58,   72,   72,   38,   38,

       73,   73,  182,   55,  150,   58,   57,   57,   38,   40,
       56,   38,   41,   42,  110,   39,   44,   57,   74,   74,
       57,   96,   71,   58,   75,   75,   83,   83,  111,  111,
       73,   76,   76,   70,   68,   57,   61,   61,   77,   77,
       78,   78,   72,   80,   80,  123,  123,   90,   90,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   75,
       74,   79,   79,   82,   82,   61,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   64,   64,   52,   76,
       81,   81,   85,   85,   77,   90,   80,   64,   78,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   65,

       65,  151,  151,  152,  152,  183,  183,   48,   79,   43,
       82,   25,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   84,   84,   85,   81,   89,   89,   65,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   86,
       86,   87,   87,   88,   88,  270,   89,   91,   91,   92,
       92,   24,   84,   23,   93,   93,   95,   95,   21,   84,
      270,   89,   94,   94,  112,  112,   14,  113,  113,   13,
       99,   99,  100,  100,   10,   86,  114,  114,    6,   88,
        3,   99,    2,  100,   87,   86,   86,   92,  117,  117,

        0,   91,   93,    0,   93,   92,   88,  113,   95,   99,
       94,  100,  101,  101,  184,  184,    0,  112,  115,  115,
      114,  116,  116,  101,  120,  120,  125,  125,  117,  101,
        0,  118,  118,  124,  124,  119,  119,  121,  121,  126,
      126,  101,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  118,  115,  125,  120,    0,  116,  116,  119,
        0,  121,  122,  122,    0,  126,  124,  127,  127,  128,
      128,  129,  129,  130,  130,  131,  131,  132,  132,  133,
      133,  134,  134,  135,  135,    0,  136,  136,  137,  137,

      138,  138,  122,    0,  139,  139,  141,  141,  153,  153,
      154,  154,  140,  140,    0,  127,  142,  142,  155,  155,
        0,  132,  144,  144,  145,  145,  128,  131,  130,  129,
      136,  157,  157,  144,    0,  145,  133,  139,  138,  134,
      135,  137,  140,  146,  146,    0,  141,  153,  142,  156,
      156,  144,    0,  145,  146,    0,  155,  154,  158,  158,
      159,  159,    0,  146,  160,  160,  161,  161,  162,  162,
        0,  157,  146,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  163,  163,  164,  164,  156,  165,  165,

      166,  166,    0,  158,  168,  168,  160,  159,  167,  167,
      171,  171,  161,  162,    0,  169,  169,  170,  170,  172,
      172,  173,  173,  174,  174,  175,  175,  185,  185,  176,
      176,    0,  165,  177,  177,    0,  168,    0,  163,    0,
      176,    0,  164,  166,  177,    0,  167,  169,  202,  202,
      170,    0,  171,  178,  178,  172,    0,  174,  176,  202,
      190,  190,  177,    0,  178,  175,  186,  186,  173,  185,
      178,  187,  187,  188,  188,  189,  189,  202,  191,  191,
      192,  192,  178,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  181,  181,  181,  181,  181,  181,  181,

      181,  181,  181,  193,  193,  187,  186,  190,    0,  189,
      194,  194,  195,  195,    0,  188,  191,  196,  196,  197,
      197,    0,  192,  198,  198,  199,  199,  200,  200,  201,
      201,  203,  203,  209,  209,    0,  193,  204,  204,  212,
      212,    0,  203,    0,  195,  194,  226,  226,  204,    0,
      210,  210,  211,  211,  228,  228,  197,  198,  204,    0,
      203,  217,  217,    0,  196,  200,  204,  199,  213,  213,
        0,  214,  214,  215,  215,  216,  216,  201,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  210,  211,

        0,  217,  213,  214,  218,  218,  219,  219,  215,  216,
      220,  220,  221,  221,    0,  230,  230,  219,    0,  229,
      229,  220,    0,  221,  241,  241,  242,  242,  221,  227,
      227,    0,  231,  231,    0,  219,    0,  218,    0,  220,
        0,  221,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  230,  227,  229,  231,  232,  232,  233,  233,
      234,  234,  235,  235,  236,  236,  250,  250,  259,  259,
        0,  234,    0,  235,    0,  236,  265,  265,  269,  269,
      271,  271,    0,  236,  273,  273,  274,  274,    0,  234,

      232,  235,  233,  236,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  243,  244,  244,  243,  243,  245,
      245,  246,  246,  275,  275,    0,  244,  276,  276,    0,
      245,    0,  246,  277,  277,  278,  278,    0,  246,  279,
      279,  243,  280,  280,  244,  281,  281,    0,  245,    0,
      246,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  249,  249,  249,  249,  249,  249,  249,  249,  253,
      253,  254,  254,  255,  255,  282,  282,  283,  283,    0,

      253,    0,  254,    0,  255,  284,  284,  285,  285,  286,
      286,  287,  287,  288,  288,  289,  289,    0,  253,    0,
      254,    0,  255,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  261,  261,  262,  262,  267,  267,  268,
      268,  290,  290,    0,  261,    0,  262,    0,  267,    0,
      268,  291,  291,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  261,    0,  262,    0,  267,    0,  268,  293,
      293,  293,  293,  293,  293,  293,  293,  294,    0,    0,
      294,  294,  295,    0,  295,  295,  295,  295,  295,  295,

      296,    0,  296,  297,    0,  297,  297,  297,  298,    0,
        0,  298,  298,  299,  299,    0,  299,  299,  299,  299,
      299,  300,    0,  300,  300,  300,  300,  300,  300,  301,
        0,  301,  301,  302,    0,  302,  302,  303,    0,  303,
      303,  304,  304,  304,  304,  304,  304,  304,  304,  305,
        0,  305,  305,  305,  305,  305,  305,  307,    0,    0,
      307,  307,  308,    0,    0,  308,  309,    0,  309,  309,
      310,    0,  310,  310,  312,    0,    0,  312,  312,  313,
        0,  313,  313,  314,    0,  314,  314,  316,    0,    0,
      316,  316,  317,    0,  317,  317,  318,    0,  318,  318,

      320,    0,    0,  320,  320,  321,    0,  321,  321,  322,
        0,  322,  322,  324,    0,    0,  324,  324,  325,    0,
      325,  325,  326,    0,  326,  326,  328,    0,    0,  328,
      328,  329,    0,  329,  329,  330,    0,  330,  330,  331,
        0,    0,  331,  331,  332,    0,  332,  332,  333,    0,
      333,  333,  334,    0,    0,  334,  334,  335,    0,  335,
      335,  335,  335,  335,  335,  336,    0,  336,  336,  337,
        0,  337,  337,  338,    0,    0,  338,  338,  339,    0,
      339,  339,  340,    0,  340,  340,  341,    0,    0,  341,
      341,  342,    0,    0,  342,  342,  343,    0,    0,  343,

      343,  344,    0,    0,  344,  344,  345,    0,    0,  345,
      345,  346,    0,    0,  346,  346,  347,    0,    0,  347,
      347,  348,    0,    0,  348,  348,  349,    0,    0,  349,
      349,  350,    0,    0,  350,  350,  351,    0,    0,  351,
      351,  352,    0,    0,  352,  352,  353,    0,    0,  353,
      353,  354,    0,    0,  354,  354,  355,    0,    0,  355,
      355,  356,    0,    0,  356,  356,  357,    0,    0,  357,
      357,  358,    0,    0,  358,  358,  359,    0,    0,  359,
      359,  360,    0,    0,  360,  360,  361,    0,    0,  361,
      361,  292,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lexicalAnalyser.l"
#define INITIAL 0
#line 3 ".\\lexicalAnalyser.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define TABLE_SIZE 100003
#define MAX_SYMBOLS 1000000

int line_num = 1;

char * locations[MAX_SYMBOLS];
int symTableSize=0;

struct lines{
    int lineno; // stores the line-number
    struct lines*next;
};
struct SymbolTableEntry {
    char * name; //identifier
    char * type;
    int size;
    struct SymbolTableEntry * next;
    struct lines * head; //head of the linenumbers list
    struct lines *  tail; //tail of the linenumbers list
};

struct SymbolTable {
    struct SymbolTableEntry * symTable[TABLE_SIZE];
};

struct SymbolTable Table;

//Hash Function
int hashfunction(char *s) {
    int pp = 101;
    int mod = TABLE_SIZE;
    int val = 0;
    int n = strlen(s);
    int p = 1;
    for (int i = 0; i < n; i++) {
        int c = s[i];
        val = (val + ((c * p) % mod)) % mod;
        p = (p * pp) % mod;
    }
    return val;
}

// Function to insert a key-value pair (doesnt exist) into the SymbolTable 
void insert1(char* key,char * type,int linenumber) {
    int index = hashfunction(key);

    // Create a new entry
    struct SymbolTableEntry* new_entry = (struct SymbolTableEntry*)malloc(sizeof(struct SymbolTableEntry));

    new_entry->name = strdup(key); // Duplicate the key string
    new_entry->type = strdup(type); // Duplicate the type string
    new_entry->size = strlen(key); 
    new_entry->next = Table.symTable[index];
    new_entry->head = (struct lines *)malloc(sizeof(struct lines));
    new_entry->head->lineno = linenumber;
    new_entry->head->next = NULL;
    new_entry->tail = new_entry->head;
    Table.symTable[index] = new_entry;
    locations[symTableSize++]=strdup(key);
}

//Function to append an entry for key-value pair that already exists in the SymbolTable
void insert2(struct SymbolTableEntry* entry,int linenumber){
    struct lines * new_node = (struct lines *)malloc(sizeof(struct lines));
    new_node->lineno = linenumber;
    new_node->next = NULL;
    entry->tail->next = new_node;
    entry->tail = new_node;
}

// Function to Lookup
struct SymbolTableEntry *  lookup(char* key) {
    int index = hashfunction(key);
    struct SymbolTableEntry* entry = Table.symTable[index];
    while(entry != NULL)
        {
            if(strcmp(entry->name,key) == 0)return entry;
            entry = entry->next;
        }
        // Key not found
        return NULL;
}

void processToken(const char* token,char *category,int linenumber) {
    char* buffer = (char*)malloc(strlen(token) + 1);
    strcpy(buffer, token);
    //printf("%s : %s\n", category, buffer);
    struct SymbolTableEntry* found = lookup(buffer);
    if (found == NULL) {
        insert1(buffer, category,linenumber);
    }
    else{
        insert2(found,linenumber);
    }
    free(buffer);
}

#line 898 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 105 ".\\lexicalAnalyser.l"


#line 1055 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 293 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1392 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tHEADER FILE \t%20d\n", yytext,line_num);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 ".\\lexicalAnalyser.l"
{line_num++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tKEYWORD \t%24d\n", yytext,line_num);};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 ".\\lexicalAnalyser.l"
{
    processToken(yytext, "Identifier", line_num);
    fprintf(yyout, "%30s \t--->\tIDENTIFIER \t%22d\n", yytext, line_num);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 ".\\lexicalAnalyser.l"
{
   printf("\n\nERROR : Constant '%s' is invalid\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Identifier '%s' is too long\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"Integer Constants",line_num);
    fprintf(yyout,"%30s \t--->\tINTERGER CONSTANT \t%14d\n", yytext,line_num);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 131 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Integer Limit Exceed\nline no : %d",line_num);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 135 ".\\lexicalAnalyser.l"
{
    printf("\n\nERROR : Identifier '%s' is invalid\nline no : %d", yytext, line_num);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 139 ".\\lexicalAnalyser.l"
{
    fprintf(yyout,"%30s \t--->\tCHARACTER CONSTANT \t%13d\n", yytext,line_num);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 143 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"Floating-Point Constants",line_num);
    fprintf(yyout,"%30s \t--->\tFLOATING-POINT CONSTANT \t%30d\n", yytext,line_num);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 148 ".\\lexicalAnalyser.l"
{
    processToken(yytext,"String Literal",line_num);
    fprintf(yyout,"%30s \t--->\tSTRING LITERAL \t%18d\n", yytext,line_num);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 153 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tPARENTHESIS \t%20d\n", yytext,line_num+1);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 155 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tSEMICOLON \t%22d\n", yytext,line_num+1);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tCOMMA \t%26d\n", yytext,line_num+1);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tARITHMETIC OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tUNARY OPERATOR \t%18d\n", yytext,line_num+1);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tLOGICAL OPERATOR \t%16d\n", yytext,line_num+1);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tBIT-WISE OPERATOR \t%14d\n", yytext,line_num+1);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 167 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tRELATIONAL OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tASSIGNMENT OPERATOR \t%12d\n", yytext,line_num+1);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 171 ".\\lexicalAnalyser.l"
{fprintf(yyout,"%30s \t--->\tSINGLELINE COMMENT \t%14d\n",yytext,line_num+1);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 173 ".\\lexicalAnalyser.l"
{printf("\n\nERROR : Invalid Comment -> does not have a valid starting /* '%s' \nline no : %d", yytext, line_num);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 175 ".\\lexicalAnalyser.l"
{
    int k  = 2;
    int err = 0;
    int found  = 0;
    while(k<yyleng){
        if(yytext[k]=='/' && (k+1)<yyleng && yytext[k+1]=='*'){
            err = 1;
        }
        if(yytext[k]=='*' && (k+1)<yyleng && yytext[k+1]=='/'){
            found = 1;
            break;
        }
        ++k;
    }
    if(err == 0 && found==1){
        int kk  = k;
        kk+=2;
        for (int i = 0; i < kk; i++) {
            if (yytext[i] == '\n') {
                ++line_num;
            } else if (yytext[i] != ' ') {
                int j = i;
                char temp[100];
                int temp_index = 0;
                while (j < kk && yytext[j] != '\n' && yytext[j] != ' ') {
                    temp[temp_index] = yytext[j];
                    temp_index++;
                    j++;
                }
                temp[temp_index] = '\0';
                fprintf(yyout, "%30s \t--->\tMULTILINE COMMENT \t%14d\n", temp, line_num);
                i = j - 1;
            }   
        }
    }
    else if(err == 1){
        printf("\n\nERROR : Invalid Comment -> nested comments are not supported */ '%s' \nline no : %d", yytext, line_num);
    }
    else{
        printf("\n\nERROR : Invalid Comment -> does not end with */ '%s' \nline no : %d", yytext, line_num);
    }
    for(int i = yyleng-1;i>k+1;--i){
            unput(yytext[i]);
    }

}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 222 ".\\lexicalAnalyser.l"
{printf("\n\nERROR : String '%s' is invalid\nline no : %d", yytext, line_num);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 224 ".\\lexicalAnalyser.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 225 ".\\lexicalAnalyser.l"
ECHO;
	YY_BREAK
#line 1341 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 293 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 293 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 292);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 225 ".\\lexicalAnalyser.l"


int yywrap(){
    return 1;
}

int main(){
    for (int i=0; i<TABLE_SIZE;i++) {
        Table.symTable[i] = NULL;
    }
    yyin = fopen("inputSix.txt","r");
    yyout=fopen("ListOfTokens.txt","w");
    fprintf(yyout,"\n-------------------------------------------------------------------------------------------------------\n");
    fprintf(yyout,"%30s \t--->\t %s \t%30s", "Lexeme", 
    "Token","Line Number");
    fprintf(yyout,"\n-------------------------------------------------------------------------------------------------------\n");
    yylex();
    printf("\n\nSYMBOL TABLE\n\n");
    printf("%-15s  %-10s  %-20s  %-20s\n", "Identifier", 
    "Size", "Type", "Line Numbers");
    printf("---------------------------------------------------------------\n");

    for (int i = 0; i < symTableSize; i++) {
        struct SymbolTableEntry * entry = lookup(locations[i]);
        printf("%-15s  %-10d  %-20s  [ ", entry->name, entry->size, entry->type);
        struct lines* h = entry->head;
        while(h){
            printf("%d ", h->lineno);
            h = h->next;
        }
        printf("]\n");
    }
    printf("---------------------------------------------------------------\n");
    printf("\n\n");
    fclose(yyin);
    return 0;
}