/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_accept[306] =
    {   0,
        0,    0,   75,   73,   72,   71,   52,   73,   73,   49,
       43,   73,   37,   38,   47,   45,   69,   46,   35,   48,
       28,   28,   28,   28,   70,   68,   59,   36,   60,   27,
       27,   41,   42,   54,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   39,
       53,   40,   72,   58,    0,   32,    0,    0,   51,   62,
        0,   66,   44,   64,    0,   28,   28,   28,   65,   34,
        0,   30,   67,    0,   28,   28,   28,   56,    0,   55,
       57,   27,   27,   63,   27,   27,   27,   27,   27,   27,
       27,   27,   27,    6,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   61,   50,    0,
       33,    0,    0,   30,   29,   28,   28,   28,    0,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   13,
       17,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,    0,   31,   29,   28,   28,   28,
        0,   27,    5,   27,   19,   17,   27,   27,   27,   27,
        7,   27,    0,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   12,   27,    0,   29,   28,   28,   28,
       26,   27,    8,    0,   11,   27,   27,   27,    0,   17,
        0,    0,   27,   27,   27,   24,   27,   27,   27,   27,

       21,   27,   14,    0,   29,   28,   28,   28,   27,   27,
       27,   17,    0,    0,   16,    0,    0,    1,   23,   22,
        2,   20,   18,   27,   27,    0,   29,   28,   28,   28,
       27,   27,   10,    4,    0,    0,    3,   27,   25,   29,
       28,   28,   28,   27,    9,    0,    0,   17,   28,   28,
       28,   27,    0,    0,   15,   28,   27,    0,   27,    0,
       27,    0,   27,    0,   27,    0,   27,    0,   27,    0,
       27,    0,   27,    0,   27,    0,   27,    0,   27,    0,
       27,    0,   27,    0,   27,    0,   27,    0,   27,    0,
       27,    0,   27,    0,   27,    0,   27,    0,   27,    0,

        0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   24,   25,   26,   27,   28,   29,   30,
       31,   32,    1,    1,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   34,   33,   35,   33,   33,
       33,   33,   33,   33,   36,   33,   33,   33,   33,   33,
       37,    1,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   33,   50,   51,   52,   53,
       54,   55,   33,   56,   57,   58,   59,   60,   61,   33,
       62,   63,   64,   65,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        8,    1,    9,    9,    9,    9,    1,    1,    1,   10,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[390] =
    {   0,
        0,    0,  704,  823,   65,  823,  671,  695,   66,  823,
       62,    0,  823,  823,  665,   58,  823,  100,  823,   60,
      675,  673,   57,  672,  823,  823,  653,  649,  647,    0,
      641,  823,  823,  641,  612,   34,   36,  615,   29,   33,
      611,  619,  600,  609,   49,  591,  595,  590,  594,  823,
       53,  823,   83,  823,  635,  630,   92,  579,  823,  823,
      620,  823,  823,  823,  612,  607,   80,  603,  823,  823,
      605,    0,  823,  123,  600,  134,   82,  823,   78,  823,
      823,    0,  578,  823,  563,  549,  564,  547,  550,  535,
      536,  534,  528,    0,  524,  528,  525,  523,  512,  528,

      501,  504,  509,  502,   57,  503,  499,  823,  823,  503,
      823,  532,  522,    0,  143,  519,  111,  517,  485,    0,
      494,  484,  477,  462,   54,  475,  473,  465,  466,    0,
      499,  454,  449,  442,  433,  436,  441,  423,  422,  434,
      420,  422,  423,  414,  413,  823,  152,  442,  163,  172,
      424,    0,    0,  403,    0,  446,  388,  396,  385,  392,
      438,  380,  129,  381,  373,  372,  379,  368,  375,  372,
      361,  346,  344,  382,  338,  321,  177,  353,  112,  343,
      823,    0,    0,  353,    0,  303,  304,  309,  201,  349,
      202,  203,  309,  267,  257,    0,  263,  250,  220,  222,

        0,  213,    0,  221,  196,  232,  234,  189,    0,  189,
      189,  242,  197,  220,  823,  221,  222,    0,    0,    0,
        0,    0,    0,  184,  184,  183,  215,  210,  247,  195,
        0,  107,    0,  823,  241,  258,    0,   96,  823,  823,
      119,  295,  256,    0,    0,  259,  276,  126,  100,  108,
       96,    0,  277,  278,  823,   91,    0,  279,    0,  280,
        0,  281,    0,  282,    0,  290,    0,  291,    0,  292,
        0,  293,    0,  294,    0,  295,    0,  296,    0,  319,
        0,  320,    0,  321,    0,  322,    0,  323,    0,  324,
        0,  325,    0,  333,    0,  334,    0,  335,  823,  336,

      337,  338,  339,  347,  823,  358,  368,  374,  377,  380,
      380,  383,  393,  403,  409,  410,  416,  419,  422,  423,
      429,  430,  438,  444,  447,  450,  451,  459,  465,  466,
      474,  480,  483,  486,  487,  495,  501,  502,  510,  516,
      519,  520,  528,  532,  540,  544,  552,  556,  564,  568,
      576,  580,  588,  592,  600,  604,  612,  616,  624,  628,
      636,  640,  648,  652,  660,  664,  672,  676,  684,  688,
      696,  700,  708,  712,  720,  724,  732,  736,  744,  748,
      756,  760,  768,  772,  780,  788,  796,  804,  812
    } ;

static yyconst short int yy_def[390] =
    {   0,
      305,    1,  305,  305,  305,  305,  305,  306,  305,  305,
      305,  307,  305,  305,  305,  305,  305,  305,  305,  305,
      308,  309,  310,  310,  305,  305,  311,  305,  305,  312,
      312,  305,  305,  305,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  305,
      305,  305,  305,  305,  306,  306,  305,  305,  305,  305,
      305,  305,  305,  305,  308,  309,  310,  310,  305,  305,
      313,  314,  305,  305,  315,  305,   76,  305,  311,  305,
      305,  316,  316,  305,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  305,  305,  305,
      305,  313,  305,  314,  305,  317,  318,  319,  305,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  305,  305,  305,  321,  305,  149,
      305,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  323,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  305,  305,  324,  325,  326,
      305,  327,  327,  323,  327,  327,  327,  327,  305,  327,
      328,  328,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  305,  305,  329,  305,  207,  330,  330,
      330,  330,  305,  305,  305,  331,  331,  330,  330,  330,
      330,  330,  330,  330,  330,  305,  305,  332,  333,  334,
      335,  335,  335,  305,  336,  336,  335,  335,  305,  305,
      337,  305,  242,  338,  338,  339,  339,  338,  340,  243,
      341,  342,  343,  305,  305,  341,  344,  345,  346,  347,
      348,  349,  350,  351,  352,  353,  354,  355,  356,  357,
      358,  359,  360,  361,  362,  363,  364,  365,  366,  367,
      368,  369,  370,  371,  372,  373,  374,  375,  376,  377,
      378,  379,  380,  381,  382,  383,  384,  385,  305,  386,

      387,  388,  389,  305,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_nxt[890] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   24,   24,   24,   24,   25,   26,   27,
       28,   29,   30,   30,   31,   30,   32,   33,   34,   30,
       30,   35,   36,   37,   38,   39,   30,   30,   40,   30,
       41,   42,   30,   30,   43,   44,   45,   46,   47,   48,
       49,   30,   30,   50,   51,   52,   53,   57,   53,   57,
       59,   63,   71,   74,   86,   76,   76,   72,   94,   92,
       89,   87,   93,  108,   53,   95,   53,   88,   64,   90,
       73,  100,   60,   57,  119,   57,   74,  101,   76,   76,

      118,  118,  118,  118,  118,  141,  102,   74,  305,  103,
      157,  158,   74,  142,   58,   63,   74,  109,   65,   66,
       67,   68,   68,   68,   68,   68,   68,   74,   74,  184,
       69,   70,  163,   65,   65,   74,  150,  150,  208,  248,
       58,  115,  115,  115,  115,  115,  115,  115,  115,  115,
       74,  245,  117,  117,  117,  117,  117,  118,  118,  118,
      118,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      177,  177,  177,  177,  177,  177,  177,  177,  177,   74,
      192,  179,  179,  179,  179,  179,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  189,  214,  214,  230,  230,  230,
      230,   74,  215,  215,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  214,  214,  214,   74,  239,  238,  237,
      215,  215,  215,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  234,  217,  214,  184,  233,  232,   74,  213,
       74,  215,  229,  229,  229,  229,  230,  230,  230,  230,
      230,  214,  214,   74,  226,  225,  224,  223,  215,  215,
      236,  243,  243,  243,  251,  251,  251,  251,  251,  254,
      214,  254,  214,  214,  214,  214,  255,  215,  255,  215,
      215,  215,  215,  214,  214,  214,  214,  214,  214,  214,

      215,  215,  215,  215,  215,  215,  215,  222,  221,  220,
      247,   74,  219,  250,  250,  250,  250,  250,  251,  251,
      251,  251,  214,  214,  214,  214,  214,  214,  214,  215,
      215,  215,  215,  215,  215,  215,  214,  214,  214,  214,
      214,  214,  214,  215,  215,  215,  215,  215,  215,  215,
      214,  218,  184,  212,  211,  210,  184,  215,   55,   74,
       55,   55,   55,   55,   55,   55,   55,   55,   61,   74,
       61,   61,   61,   61,   61,   61,   61,   61,   65,  204,
       65,   75,  203,   75,   77,  163,   77,   79,   79,   82,
      202,   82,   82,  112,  112,  112,  112,  112,  201,  112,

      112,  112,  112,  114,  200,  114,  114,  114,  114,  114,
      114,  114,  114,  116,  199,  116,  120,  198,  120,  120,
      148,  197,  148,  149,  196,  149,  150,  195,  150,  152,
      194,  152,  152,  178,  193,  178,  182,  190,  182,  182,
      191,  189,  188,  187,  186,  185,  191,  191,  206,  184,
      206,  207,  183,  207,  208,  181,  208,  209,   74,  209,
      209,  216,  216,  176,  175,  216,  174,  216,  216,  228,
      173,  228,  231,  172,  231,  231,  235,  235,  171,  170,
      235,  169,  235,  235,  241,  168,  241,  242,  167,  242,
      243,  166,  243,  244,  165,  244,  244,  246,  246,  164,

      156,  246,  163,  246,  246,  249,  162,  249,  252,  161,
      252,  252,  253,  253,  160,  159,  253,  156,  253,  253,
      256,  155,  256,   65,  154,   65,  257,  153,  257,  257,
      258,  258,  151,   74,  258,   74,  258,  258,  259,  146,
      259,  259,  260,  260,  113,  145,  260,  144,  260,  260,
      261,  143,  261,  261,  262,  262,  140,  139,  262,  138,
      262,  262,  263,  137,  263,  263,  264,  264,  136,  135,
      264,  134,  264,  264,  265,  133,  265,  265,  266,  266,
      132,  131,  266,  130,  266,  266,  267,  129,  267,  267,
      268,  268,  128,  127,  268,  126,  268,  268,  269,  125,

      269,  269,  270,  270,  124,  123,  270,  122,  270,  270,
      271,  121,  271,  271,  272,  272,   74,  113,  272,   74,
      272,  272,  273,   74,  273,  273,  274,  274,   74,  111,
      274,  110,  274,  274,  275,   56,  275,  275,  276,  276,
       56,  107,  276,  106,  276,  276,  277,  105,  277,  277,
      278,  278,  104,   99,  278,   98,  278,  278,  279,   97,
      279,  279,  280,  280,   96,   91,  280,   85,  280,  280,
      281,   84,  281,  281,  282,  282,   83,   81,  282,   80,
      282,  282,  283,   78,  283,  283,  284,  284,   74,   74,
      284,   74,  284,  284,  285,   62,  285,  285,  286,  286,

       56,   54,  286,  305,  286,  286,  287,  305,  287,  287,
      288,  288,  305,  305,  288,  305,  288,  288,  289,  305,
      289,  289,  290,  290,  305,  305,  290,  305,  290,  290,
      291,  305,  291,  291,  292,  292,  305,  305,  292,  305,
      292,  292,  293,  305,  293,  293,  294,  294,  305,  305,
      294,  305,  294,  294,  295,  305,  295,  295,  296,  296,
      305,  305,  296,  305,  296,  296,  297,  305,  297,  297,
      298,  298,  305,  305,  298,  305,  298,  298,  299,  305,
      299,  299,  300,  300,  305,  305,  300,  305,  300,  300,
      301,  301,  305,  305,  301,  305,  301,  301,  302,  302,

      305,  305,  302,  305,  302,  302,  303,  303,  305,  305,
      303,  305,  303,  303,  304,  304,  305,  305,  304,  305,
      304,  304,    3,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_chk[890] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    9,    5,    9,
       11,   16,   20,   23,   36,   23,   23,   20,   40,   39,
       37,   36,   39,   51,   53,   40,   53,   36,   16,   37,
       20,   45,   11,   57,   79,   57,   67,   45,   67,   67,

       77,   77,   77,   77,   77,  105,   45,  256,   79,   45,
      125,  125,  251,  105,    9,   18,  249,   51,   18,   18,
       18,   18,   18,   18,   18,   18,   18,  117,  179,  248,
       18,   18,  163,  250,  250,  241,  117,  117,  179,  238,
       57,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       76,  232,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  149,
      163,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      150,  150,  150,  150,  150,  177,  177,  177,  177,  177,

      177,  177,  177,  177,  189,  191,  192,  208,  208,  208,
      208,  230,  191,  192,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  214,  216,  217,  228,  226,  225,  224,
      214,  216,  217,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  213,  192,  235,  212,  211,  210,  206,  189,
      207,  235,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  236,  246,  229,  204,  202,  200,  199,  236,  246,
      217,  229,  229,  229,  243,  243,  243,  243,  243,  247,
      253,  254,  258,  260,  262,  264,  247,  253,  254,  258,
      260,  262,  264,  266,  268,  270,  272,  274,  276,  278,

      266,  268,  270,  272,  274,  276,  278,  198,  197,  195,
      236,  242,  194,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  280,  282,  284,  286,  288,  290,  292,  280,
      282,  284,  286,  288,  290,  292,  294,  296,  298,  300,
      301,  302,  303,  294,  296,  298,  300,  301,  302,  303,
      304,  193,  190,  188,  187,  186,  184,  304,  306,  180,
      306,  306,  306,  306,  306,  306,  306,  306,  307,  178,
      307,  307,  307,  307,  307,  307,  307,  307,  308,  176,
      308,  309,  175,  309,  310,  174,  310,  311,  311,  312,
      173,  312,  312,  313,  313,  313,  313,  313,  172,  313,

      313,  313,  313,  314,  171,  314,  314,  314,  314,  314,
      314,  314,  314,  315,  170,  315,  316,  169,  316,  316,
      317,  168,  317,  318,  167,  318,  319,  166,  319,  320,
      165,  320,  320,  321,  164,  321,  322,  162,  322,  322,
      323,  161,  160,  159,  158,  157,  323,  323,  324,  156,
      324,  325,  154,  325,  326,  151,  326,  327,  148,  327,
      327,  328,  328,  145,  144,  328,  143,  328,  328,  329,
      142,  329,  330,  141,  330,  330,  331,  331,  140,  139,
      331,  138,  331,  331,  332,  137,  332,  333,  136,  333,
      334,  135,  334,  335,  134,  335,  335,  336,  336,  133,

      132,  336,  131,  336,  336,  337,  129,  337,  338,  128,
      338,  338,  339,  339,  127,  126,  339,  124,  339,  339,
      340,  123,  340,  341,  122,  341,  342,  121,  342,  342,
      343,  343,  119,  118,  343,  116,  343,  343,  344,  113,
      344,  344,  345,  345,  112,  110,  345,  107,  345,  345,
      346,  106,  346,  346,  347,  347,  104,  103,  347,  102,
      347,  347,  348,  101,  348,  348,  349,  349,  100,   99,
      349,   98,  349,  349,  350,   97,  350,  350,  351,  351,
       96,   95,  351,   93,  351,  351,  352,   92,  352,  352,
      353,  353,   91,   90,  353,   89,  353,  353,  354,   88,

      354,  354,  355,  355,   87,   86,  355,   85,  355,  355,
      356,   83,  356,  356,  357,  357,   75,   71,  357,   68,
      357,  357,  358,   66,  358,  358,  359,  359,   65,   61,
      359,   58,  359,  359,  360,   56,  360,  360,  361,  361,
       55,   49,  361,   48,  361,  361,  362,   47,  362,  362,
      363,  363,   46,   44,  363,   43,  363,  363,  364,   42,
      364,  364,  365,  365,   41,   38,  365,   35,  365,  365,
      366,   34,  366,  366,  367,  367,   31,   29,  367,   28,
      367,  367,  368,   27,  368,  368,  369,  369,   24,   22,
      369,   21,  369,  369,  370,   15,  370,  370,  371,  371,

        8,    7,  371,    3,  371,  371,  372,    0,  372,  372,
      373,  373,    0,    0,  373,    0,  373,  373,  374,    0,
      374,  374,  375,  375,    0,    0,  375,    0,  375,  375,
      376,    0,  376,  376,  377,  377,    0,    0,  377,    0,
      377,  377,  378,    0,  378,  378,  379,  379,    0,    0,
      379,    0,  379,  379,  380,    0,  380,  380,  381,  381,
        0,    0,  381,    0,  381,  381,  382,    0,  382,  382,
      383,  383,    0,    0,  383,    0,  383,  383,  384,    0,
      384,  384,  385,  385,    0,    0,  385,    0,  385,  385,
      386,  386,    0,    0,  386,    0,  386,  386,  387,  387,

        0,    0,  387,    0,  387,  387,  388,  388,    0,    0,
      388,    0,  388,  388,  389,  389,    0,    0,  389,    0,
      389,  389,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "semanticAnalysis.l"
#define INITIAL 0
#line 2 "semanticAnalysis.l"
    #include <stdio.h>
    #include "y.tab.h"
    int yylinenumber=1;
    int intval = 0;
#line 681 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 8 "semanticAnalysis.l"

#line 834 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 823 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "semanticAnalysis.l"
{return MALLOC;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 "semanticAnalysis.l"
{return SIZEOF;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "semanticAnalysis.l"
{return TYPEDEF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 "semanticAnalysis.l"
{return ELIF;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 "semanticAnalysis.l"
{return NULLT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 "semanticAnalysis.l"
{return IF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "semanticAnalysis.l"
{return ELSE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 "semanticAnalysis.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 "semanticAnalysis.l"
{return CONTINUE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 "semanticAnalysis.l"
{return DEFAULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 "semanticAnalysis.l"
{return CONST;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 "semanticAnalysis.l"
{return VOID;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "semanticAnalysis.l"
{return FOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "semanticAnalysis.l"
{return WHILE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 "semanticAnalysis.l"
{return MAIN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 24 "semanticAnalysis.l"
{
    yylval.value=strdup(yytext);
    return FUN_START;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "semanticAnalysis.l"
{yylval.type=strdup(yytext);return TYPE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "semanticAnalysis.l"
{return SWITCH;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "semanticAnalysis.l"
{return CASE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "semanticAnalysis.l"
{yylval.type=strdup("struct");return STRUCT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "semanticAnalysis.l"
{yylval.type=strdup("union");return UNION;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "semanticAnalysis.l"
{return RETURN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "semanticAnalysis.l"
{return PRINTF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "semanticAnalysis.l"
{return SCANF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 "semanticAnalysis.l"
{return INCLUDE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 "semanticAnalysis.l"
{return PREDEF_HEADER;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 "semanticAnalysis.l"
{yylval.value=strdup(yytext);return ID;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 38 "semanticAnalysis.l"
{
    int p = 1;
    intval = 0;
    for(int i =yyleng - 1;i>=0;i--)
    {
        intval += (yytext[i] - '0') * p;
        p*=10;
    }
    yylval.type=strdup("int");return INTEGER;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "semanticAnalysis.l"
{yylval.type=strdup("float");return FLOATING_NUM;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "semanticAnalysis.l"
{return SL_COMMENT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "semanticAnalysis.l"
{return ML_COMMENT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "semanticAnalysis.l"
{yylval.type=strdup("string");return STRING;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "semanticAnalysis.l"
{yylval.type=strdup("char");return CHAR_CONST;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "semanticAnalysis.l"
{return ARROW;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 "semanticAnalysis.l"
{return DOT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 "semanticAnalysis.l"
{return EQUALTO;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 56 "semanticAnalysis.l"
{return OPEN_BRACK;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 57 "semanticAnalysis.l"
{return CLOSE_BRACK;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 58 "semanticAnalysis.l"
{return OPEN_FLOWER;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "semanticAnalysis.l"
{return CLOSE_FLOWER;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 "semanticAnalysis.l"
{return OPEN_SQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 61 "semanticAnalysis.l"
{return CLOSE_SQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 62 "semanticAnalysis.l"
{return AMPERSAND;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 63 "semanticAnalysis.l"
{return UNARY_OP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 64 "semanticAnalysis.l"
{return PLUS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 65 "semanticAnalysis.l"
{return MINUS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 66 "semanticAnalysis.l"
{return MUL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 67 "semanticAnalysis.l"
{return DIV;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 68 "semanticAnalysis.l"
{return MOD;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 69 "semanticAnalysis.l"
{return OR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 70 "semanticAnalysis.l"
{return AND;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 71 "semanticAnalysis.l"
{return NOT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 72 "semanticAnalysis.l"
{return BIT_OR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 73 "semanticAnalysis.l"
{return BIT_XOR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 74 "semanticAnalysis.l"
{return ISEQUALTO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 75 "semanticAnalysis.l"
{return LTE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 76 "semanticAnalysis.l"
{return GTE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 77 "semanticAnalysis.l"
{return NE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 78 "semanticAnalysis.l"
{return LT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 79 "semanticAnalysis.l"
{return GT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 80 "semanticAnalysis.l"
{return OR_ET;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "semanticAnalysis.l"
{return AND_ET;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 82 "semanticAnalysis.l"
{return XOR_ET;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 "semanticAnalysis.l"
{return PLUS_ET;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 84 "semanticAnalysis.l"
{return MINUS_ET;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 85 "semanticAnalysis.l"
{return MUL_ET;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 86 "semanticAnalysis.l"
{return DIV_ET;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 87 "semanticAnalysis.l"
{return SEMICOLON;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 88 "semanticAnalysis.l"
{return COMMA;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 89 "semanticAnalysis.l"
{return COLON;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 90 "semanticAnalysis.l"
{++yylinenumber;};
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 91 "semanticAnalysis.l"
;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 92 "semanticAnalysis.l"
{return *yytext;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 93 "semanticAnalysis.l"
ECHO;
	YY_BREAK
#line 1298 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 93 "semanticAnalysis.l"


int yywrap(){
    return 1;
}
