/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
static yyconst short int yy_accept[304] =
    {   0,
        0,    0,   74,   72,   71,   70,   51,   72,   72,   48,
       42,   72,   36,   37,   46,   44,   68,   45,   34,   47,
       27,   27,   27,   27,   69,   67,   58,   35,   59,   26,
       26,   40,   41,   53,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   38,
       52,   39,   71,   57,    0,   31,    0,    0,   50,   61,
        0,   65,   43,   63,    0,   27,   27,   27,   64,   33,
        0,   29,   66,    0,   27,   27,   27,   55,    0,   54,
       56,   26,   26,   62,   26,   26,   26,   26,   26,   26,
       26,   26,   26,    6,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   26,   26,   26,   26,   60,   49,    0,
       32,    0,    0,   29,   28,   27,   27,   27,    0,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   12,
       16,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,    0,   30,   28,   27,   27,   27,
        0,   26,    5,   26,   18,   16,   26,   26,   26,    7,
       26,    0,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   11,   26,    0,   28,   27,   27,   27,   25,
       26,    8,    0,   26,   26,   26,    0,   16,    0,    0,
       26,   26,   26,   23,   26,   26,   26,   26,   20,   26,

       13,    0,   28,   27,   27,   27,   26,   26,   26,   16,
        0,    0,   15,    0,    0,    1,   22,   21,    2,   19,
       17,   26,   26,    0,   28,   27,   27,   27,   26,   26,
       10,    4,    0,    0,    3,   26,   24,   28,   27,   27,
       27,   26,    9,    0,    0,   16,   27,   27,   27,   26,
        0,    0,   14,   27,   26,    0,   26,    0,   26,    0,
       26,    0,   26,    0,   26,    0,   26,    0,   26,    0,
       26,    0,   26,    0,   26,    0,   26,    0,   26,    0,
       26,    0,   26,    0,   26,    0,   26,    0,   26,    0,
       26,    0,   26,    0,   26,    0,   26,    0,    0,    0,

        0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   24,   25,   26,   27,   28,   29,   30,
       31,   32,    1,    1,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   34,   33,   35,   33,   33,
       33,   33,   33,   33,   36,   33,   33,   33,   33,   33,
       37,    1,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   33,   50,   51,   52,   53,
       54,   55,   33,   56,   57,   58,   59,   60,   61,   33,
       62,   63,   64,   65,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        8,    1,    9,    9,    9,    9,    1,    1,    1,   10,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[388] =
    {   0,
        0,    0,  701,  823,   65,  823,  665,  686,   66,  823,
       62,    0,  823,  823,  659,   58,  823,  100,  823,   60,
      672,  667,   57,  663,  823,  823,  647,  646,  641,    0,
      632,  823,  823,  635,  609,   34,   36,  609,   29,   33,
      602,  613,  597,  603,   49,  582,  589,  587,  588,  823,
       53,  823,   83,  823,  626,  624,   92,  576,  823,  823,
      614,  823,  823,  823,  603,  601,   80,  600,  823,  823,
      599,    0,  823,  123,  591,  134,   82,  823,   78,  823,
      823,    0,  572,  823,  560,  543,  555,  541,  547,  529,
      527,  528,  525,    0,  518,  519,  519,  520,  506,  519,

      495,  501,  503,  493,   57,  497,  496,  823,  823,  497,
      823,  523,  516,    0,  143,  516,  111,  511,  477,    0,
      488,  477,  471,  459,  452,  466,  461,  456,  459,    0,
      491,  445,  438,  433,  423,  427,  434,  415,  413,  422,
      411,  415,  415,  405,  402,  823,  152,  433,  163,  172,
      414,    0,    0,  395,    0,  440,  394,  383,  387,  431,
      373,  129,  374,  367,  366,  372,  361,  362,  356,  347,
      333,  336,  376,  325,  301,  177,  340,  112,  339,  823,
        0,    0,  351,  301,  302,  307,  201,  309,  202,  203,
      267,  263,  255,    0,  222,  209,  218,  220,    0,  196,

        0,  204,  196,  230,  234,  189,    0,  187,  185,  226,
      183,  220,  823,  221,  222,    0,    0,    0,    0,    0,
        0,  182,  182,  167,  215,  135,  247,  123,    0,   91,
        0,  823,  241,  258,    0,   91,  823,  823,  117,  295,
      256,    0,    0,  259,  276,  126,  100,   85,   96,    0,
      277,  278,  823,   91,    0,  279,    0,  280,    0,  281,
        0,  282,    0,  290,    0,  291,    0,  292,    0,  293,
        0,  294,    0,  295,    0,  296,    0,  319,    0,  320,
        0,  321,    0,  322,    0,  323,    0,  324,    0,  325,
        0,  333,    0,  334,    0,  335,  823,  336,  337,  338,

      339,  347,  823,  358,  368,  374,  377,  380,  380,  383,
      393,  403,  409,  410,  416,  419,  422,  423,  429,  430,
      438,  444,  447,  450,  451,  459,  465,  466,  474,  480,
      483,  486,  487,  495,  501,  502,  510,  516,  519,  520,
      528,  532,  540,  544,  552,  556,  564,  568,  576,  580,
      588,  592,  600,  604,  612,  616,  624,  628,  636,  640,
      648,  652,  660,  664,  672,  676,  684,  688,  696,  700,
      708,  712,  720,  724,  732,  736,  744,  748,  756,  760,
      768,  772,  780,  788,  796,  804,  812
    } ;

static yyconst short int yy_def[388] =
    {   0,
      303,    1,  303,  303,  303,  303,  303,  304,  303,  303,
      303,  305,  303,  303,  303,  303,  303,  303,  303,  303,
      306,  307,  308,  308,  303,  303,  309,  303,  303,  310,
      310,  303,  303,  303,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  303,
      303,  303,  303,  303,  304,  304,  303,  303,  303,  303,
      303,  303,  303,  303,  306,  307,  308,  308,  303,  303,
      311,  312,  303,  303,  313,  303,   76,  303,  309,  303,
      303,  314,  314,  303,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  303,  303,  303,
      303,  311,  303,  312,  303,  315,  316,  317,  303,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  303,  303,  303,  319,  303,  149,
      303,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  321,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  303,  303,  322,  323,  324,  303,
      325,  325,  321,  325,  325,  325,  303,  325,  326,  326,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  303,  303,  327,  303,  205,  328,  328,  328,  328,
      303,  303,  303,  329,  329,  328,  328,  328,  328,  328,
      328,  328,  328,  303,  303,  330,  331,  332,  333,  333,
      333,  303,  334,  334,  333,  333,  303,  303,  335,  303,
      240,  336,  336,  337,  337,  336,  338,  241,  339,  340,
      341,  303,  303,  339,  342,  343,  344,  345,  346,  347,
      348,  349,  350,  351,  352,  353,  354,  355,  356,  357,
      358,  359,  360,  361,  362,  363,  364,  365,  366,  367,
      368,  369,  370,  371,  372,  373,  374,  375,  376,  377,
      378,  379,  380,  381,  382,  383,  303,  384,  385,  386,

      387,  303,    0,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303
    } ;

static yyconst short int yy_nxt[890] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   24,   24,   24,   24,   25,   26,   27,
       28,   29,   30,   30,   31,   30,   32,   33,   34,   30,
       30,   35,   36,   37,   38,   39,   30,   30,   40,   30,
       41,   42,   30,   30,   43,   44,   45,   46,   47,   48,
       49,   30,   30,   50,   51,   52,   53,   57,   53,   57,
       59,   63,   71,   74,   86,   76,   76,   72,   94,   92,
       89,   87,   93,  108,   53,   95,   53,   88,   64,   90,
       73,  100,   60,   57,  119,   57,   74,  101,   76,   76,

      118,  118,  118,  118,  118,  141,  102,   74,  303,  103,
       65,   65,   74,  142,   58,   63,   74,  109,   65,   66,
       67,   68,   68,   68,   68,   68,   68,   74,   74,  183,
       69,   70,  162,   74,  246,  243,  150,  150,  206,   74,
       58,  115,  115,  115,  115,  115,  115,  115,  115,  115,
       74,   74,  117,  117,  117,  117,  117,  118,  118,  118,
      118,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      176,  176,  176,  176,  176,  176,  176,  176,  176,   74,
      190,  178,  178,  178,  178,  178,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  203,  203,  203,  203,  203,

      203,  203,  203,  203,  187,  212,  212,  228,  228,  228,
      228,  237,  213,  213,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  212,  212,  212,  236,  235,  232,  183,
      213,  213,  213,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  231,  215,  212,  230,   74,  224,  223,  211,
       74,  213,  227,  227,  227,  227,  228,  228,  228,  228,
      228,  212,  212,   74,  222,  221,  220,  219,  213,  213,
      234,  241,  241,  241,  249,  249,  249,  249,  249,  252,
      212,  252,  212,  212,  212,  212,  253,  213,  253,  213,
      213,  213,  213,  212,  212,  212,  212,  212,  212,  212,

      213,  213,  213,  213,  213,  213,  213,  218,  217,  216,
      245,   74,  183,  248,  248,  248,  248,  248,  249,  249,
      249,  249,  212,  212,  212,  212,  212,  212,  212,  213,
      213,  213,  213,  213,  213,  213,  212,  212,  212,  212,
      212,  212,  212,  213,  213,  213,  213,  213,  213,  213,
      212,  210,  209,  208,  183,   74,   74,  213,   55,  202,
       55,   55,   55,   55,   55,   55,   55,   55,   61,  201,
       61,   61,   61,   61,   61,   61,   61,   61,   65,  162,
       65,   75,  200,   75,   77,  199,   77,   79,   79,   82,
      198,   82,   82,  112,  112,  112,  112,  112,  197,  112,

      112,  112,  112,  114,  196,  114,  114,  114,  114,  114,
      114,  114,  114,  116,  195,  116,  120,  194,  120,  120,
      148,  193,  148,  149,  192,  149,  150,  191,  150,  152,
      188,  152,  152,  177,  187,  177,  181,  186,  181,  181,
      189,  185,  184,  183,  182,  180,  189,  189,  204,   74,
      204,  205,  175,  205,  206,  174,  206,  207,  173,  207,
      207,  214,  214,  172,  171,  214,  170,  214,  214,  226,
      169,  226,  229,  168,  229,  229,  233,  233,  167,  166,
      233,  165,  233,  233,  239,  164,  239,  240,  163,  240,
      241,  156,  241,  242,  162,  242,  242,  244,  244,  161,

      160,  244,  159,  244,  244,  247,  158,  247,  250,  157,
      250,  250,  251,  251,  156,  155,  251,  154,  251,  251,
      254,  153,  254,   65,  151,   65,  255,   74,  255,  255,
      256,  256,   74,  146,  256,  113,  256,  256,  257,  145,
      257,  257,  258,  258,  144,  143,  258,  140,  258,  258,
      259,  139,  259,  259,  260,  260,  138,  137,  260,  136,
      260,  260,  261,  135,  261,  261,  262,  262,  134,  133,
      262,  132,  262,  262,  263,  131,  263,  263,  264,  264,
      130,  129,  264,  128,  264,  264,  265,  127,  265,  265,
      266,  266,  126,  125,  266,  124,  266,  266,  267,  123,

      267,  267,  268,  268,  122,  121,  268,   74,  268,  268,
      269,  113,  269,  269,  270,  270,   74,   74,  270,   74,
      270,  270,  271,  111,  271,  271,  272,  272,  110,   56,
      272,   56,  272,  272,  273,  107,  273,  273,  274,  274,
      106,  105,  274,  104,  274,  274,  275,   99,  275,  275,
      276,  276,   98,   97,  276,   96,  276,  276,  277,   91,
      277,  277,  278,  278,   85,   84,  278,   83,  278,  278,
      279,   81,  279,  279,  280,  280,   80,   78,  280,   74,
      280,  280,  281,   74,  281,  281,  282,  282,   74,   62,
      282,   56,  282,  282,  283,   54,  283,  283,  284,  284,

      303,  303,  284,  303,  284,  284,  285,  303,  285,  285,
      286,  286,  303,  303,  286,  303,  286,  286,  287,  303,
      287,  287,  288,  288,  303,  303,  288,  303,  288,  288,
      289,  303,  289,  289,  290,  290,  303,  303,  290,  303,
      290,  290,  291,  303,  291,  291,  292,  292,  303,  303,
      292,  303,  292,  292,  293,  303,  293,  293,  294,  294,
      303,  303,  294,  303,  294,  294,  295,  303,  295,  295,
      296,  296,  303,  303,  296,  303,  296,  296,  297,  303,
      297,  297,  298,  298,  303,  303,  298,  303,  298,  298,
      299,  299,  303,  303,  299,  303,  299,  299,  300,  300,

      303,  303,  300,  303,  300,  300,  301,  301,  303,  303,
      301,  303,  301,  301,  302,  302,  303,  303,  302,  303,
      302,  302,    3,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303
    } ;

static yyconst short int yy_chk[890] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    9,    5,    9,
       11,   16,   20,   23,   36,   23,   23,   20,   40,   39,
       37,   36,   39,   51,   53,   40,   53,   36,   16,   37,
       20,   45,   11,   57,   79,   57,   67,   45,   67,   67,

       77,   77,   77,   77,   77,  105,   45,  254,   79,   45,
      248,  248,  249,  105,    9,   18,  247,   51,   18,   18,
       18,   18,   18,   18,   18,   18,   18,  117,  178,  246,
       18,   18,  162,  239,  236,  230,  117,  117,  178,  228,
       57,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       76,  226,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  149,
      162,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      150,  150,  150,  150,  150,  176,  176,  176,  176,  176,

      176,  176,  176,  176,  187,  189,  190,  206,  206,  206,
      206,  224,  189,  190,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  212,  214,  215,  223,  222,  211,  210,
      212,  214,  215,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  209,  190,  233,  208,  204,  202,  200,  187,
      205,  233,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  234,  244,  227,  198,  197,  196,  195,  234,  244,
      215,  227,  227,  227,  241,  241,  241,  241,  241,  245,
      251,  252,  256,  258,  260,  262,  245,  251,  252,  256,
      258,  260,  262,  264,  266,  268,  270,  272,  274,  276,

      264,  266,  268,  270,  272,  274,  276,  193,  192,  191,
      234,  240,  188,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  278,  280,  282,  284,  286,  288,  290,  278,
      280,  282,  284,  286,  288,  290,  292,  294,  296,  298,
      299,  300,  301,  292,  294,  296,  298,  299,  300,  301,
      302,  186,  185,  184,  183,  179,  177,  302,  304,  175,
      304,  304,  304,  304,  304,  304,  304,  304,  305,  174,
      305,  305,  305,  305,  305,  305,  305,  305,  306,  173,
      306,  307,  172,  307,  308,  171,  308,  309,  309,  310,
      170,  310,  310,  311,  311,  311,  311,  311,  169,  311,

      311,  311,  311,  312,  168,  312,  312,  312,  312,  312,
      312,  312,  312,  313,  167,  313,  314,  166,  314,  314,
      315,  165,  315,  316,  164,  316,  317,  163,  317,  318,
      161,  318,  318,  319,  160,  319,  320,  159,  320,  320,
      321,  158,  157,  156,  154,  151,  321,  321,  322,  148,
      322,  323,  145,  323,  324,  144,  324,  325,  143,  325,
      325,  326,  326,  142,  141,  326,  140,  326,  326,  327,
      139,  327,  328,  138,  328,  328,  329,  329,  137,  136,
      329,  135,  329,  329,  330,  134,  330,  331,  133,  331,
      332,  132,  332,  333,  131,  333,  333,  334,  334,  129,

      128,  334,  127,  334,  334,  335,  126,  335,  336,  125,
      336,  336,  337,  337,  124,  123,  337,  122,  337,  337,
      338,  121,  338,  339,  119,  339,  340,  118,  340,  340,
      341,  341,  116,  113,  341,  112,  341,  341,  342,  110,
      342,  342,  343,  343,  107,  106,  343,  104,  343,  343,
      344,  103,  344,  344,  345,  345,  102,  101,  345,  100,
      345,  345,  346,   99,  346,  346,  347,  347,   98,   97,
      347,   96,  347,  347,  348,   95,  348,  348,  349,  349,
       93,   92,  349,   91,  349,  349,  350,   90,  350,  350,
      351,  351,   89,   88,  351,   87,  351,  351,  352,   86,

      352,  352,  353,  353,   85,   83,  353,   75,  353,  353,
      354,   71,  354,  354,  355,  355,   68,   66,  355,   65,
      355,  355,  356,   61,  356,  356,  357,  357,   58,   56,
      357,   55,  357,  357,  358,   49,  358,  358,  359,  359,
       48,   47,  359,   46,  359,  359,  360,   44,  360,  360,
      361,  361,   43,   42,  361,   41,  361,  361,  362,   38,
      362,  362,  363,  363,   35,   34,  363,   31,  363,  363,
      364,   29,  364,  364,  365,  365,   28,   27,  365,   24,
      365,  365,  366,   22,  366,  366,  367,  367,   21,   15,
      367,    8,  367,  367,  368,    7,  368,  368,  369,  369,

        3,    0,  369,    0,  369,  369,  370,    0,  370,  370,
      371,  371,    0,    0,  371,    0,  371,  371,  372,    0,
      372,  372,  373,  373,    0,    0,  373,    0,  373,  373,
      374,    0,  374,  374,  375,  375,    0,    0,  375,    0,
      375,  375,  376,    0,  376,  376,  377,  377,    0,    0,
      377,    0,  377,  377,  378,    0,  378,  378,  379,  379,
        0,    0,  379,    0,  379,  379,  380,    0,  380,  380,
      381,  381,    0,    0,  381,    0,  381,  381,  382,    0,
      382,  382,  383,  383,    0,    0,  383,    0,  383,  383,
      384,  384,    0,    0,  384,    0,  384,  384,  385,  385,

        0,    0,  385,    0,  385,  385,  386,  386,    0,    0,
      386,    0,  386,  386,  387,  387,    0,    0,  387,    0,
      387,  387,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\semanticAnalysis.l"
#define INITIAL 0
#line 2 ".\\semanticAnalysis.l"
    #include <stdio.h>
    #include "y.tab.h"
    int yylinenumber=1;
    int intval = 0;
#line 681 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 8 ".\\semanticAnalysis.l"

#line 834 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 304 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 823 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 ".\\semanticAnalysis.l"
{return MALLOC;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 ".\\semanticAnalysis.l"
{return SIZEOF;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 ".\\semanticAnalysis.l"
{return TYPEDEF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 ".\\semanticAnalysis.l"
{return ELIF;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 ".\\semanticAnalysis.l"
{return NULLT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 ".\\semanticAnalysis.l"
{return IF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 ".\\semanticAnalysis.l"
{return ELSE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 ".\\semanticAnalysis.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 ".\\semanticAnalysis.l"
{return CONTINUE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 ".\\semanticAnalysis.l"
{return DEFAULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 ".\\semanticAnalysis.l"
{return VOID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 ".\\semanticAnalysis.l"
{return FOR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 ".\\semanticAnalysis.l"
{return WHILE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 ".\\semanticAnalysis.l"
{return MAIN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 ".\\semanticAnalysis.l"
{
    yylval.value=strdup(yytext);
    return FUN_START;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 ".\\semanticAnalysis.l"
{yylval.type=strdup(yytext);return TYPE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 ".\\semanticAnalysis.l"
{return SWITCH;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 ".\\semanticAnalysis.l"
{return CASE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 ".\\semanticAnalysis.l"
{yylval.type=strdup("struct");return STRUCT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 ".\\semanticAnalysis.l"
{yylval.type=strdup("union");return UNION;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 ".\\semanticAnalysis.l"
{return RETURN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 ".\\semanticAnalysis.l"
{return PRINTF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 ".\\semanticAnalysis.l"
{return SCANF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 ".\\semanticAnalysis.l"
{return INCLUDE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 ".\\semanticAnalysis.l"
{return PREDEF_HEADER;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 ".\\semanticAnalysis.l"
{yylval.value=strdup(yytext);return ID;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 ".\\semanticAnalysis.l"
{
    int p = 1;
    intval = 0;
    for(int i =yyleng - 1;i>=0;i--)
    {
        intval += (yytext[i] - '0') * p;
        p*=10;
    }
    yylval.type=strdup("int");return INTEGER;
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 ".\\semanticAnalysis.l"
{yylval.type=strdup("float");return FLOATING_NUM;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 ".\\semanticAnalysis.l"
{return SL_COMMENT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 ".\\semanticAnalysis.l"
{return ML_COMMENT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 ".\\semanticAnalysis.l"
{yylval.type=strdup("string");return STRING;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 ".\\semanticAnalysis.l"
{yylval.type=strdup("char");return CHAR_CONST;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 ".\\semanticAnalysis.l"
{return ARROW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 ".\\semanticAnalysis.l"
{return DOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 ".\\semanticAnalysis.l"
{return EQUALTO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 ".\\semanticAnalysis.l"
{return OPEN_BRACK;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 56 ".\\semanticAnalysis.l"
{return CLOSE_BRACK;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 57 ".\\semanticAnalysis.l"
{return OPEN_FLOWER;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 58 ".\\semanticAnalysis.l"
{return CLOSE_FLOWER;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 ".\\semanticAnalysis.l"
{return OPEN_SQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 ".\\semanticAnalysis.l"
{return CLOSE_SQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 61 ".\\semanticAnalysis.l"
{return AMPERSAND;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 62 ".\\semanticAnalysis.l"
{return UNARY_OP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 63 ".\\semanticAnalysis.l"
{return PLUS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 64 ".\\semanticAnalysis.l"
{return MINUS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 65 ".\\semanticAnalysis.l"
{return MUL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 66 ".\\semanticAnalysis.l"
{return DIV;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 67 ".\\semanticAnalysis.l"
{return MOD;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 68 ".\\semanticAnalysis.l"
{return OR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 69 ".\\semanticAnalysis.l"
{return AND;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 70 ".\\semanticAnalysis.l"
{return NOT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 71 ".\\semanticAnalysis.l"
{return BIT_OR;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 72 ".\\semanticAnalysis.l"
{return BIT_XOR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 73 ".\\semanticAnalysis.l"
{return ISEQUALTO;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 74 ".\\semanticAnalysis.l"
{return LTE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 75 ".\\semanticAnalysis.l"
{return GTE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 76 ".\\semanticAnalysis.l"
{return NE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 77 ".\\semanticAnalysis.l"
{return LT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 78 ".\\semanticAnalysis.l"
{return GT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 79 ".\\semanticAnalysis.l"
{return OR_ET;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 80 ".\\semanticAnalysis.l"
{return AND_ET;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 ".\\semanticAnalysis.l"
{return XOR_ET;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 82 ".\\semanticAnalysis.l"
{return PLUS_ET;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 ".\\semanticAnalysis.l"
{return MINUS_ET;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 84 ".\\semanticAnalysis.l"
{return MUL_ET;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 85 ".\\semanticAnalysis.l"
{return DIV_ET;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 86 ".\\semanticAnalysis.l"
{return SEMICOLON;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 87 ".\\semanticAnalysis.l"
{return COMMA;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 88 ".\\semanticAnalysis.l"
{return COLON;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 89 ".\\semanticAnalysis.l"
{++yylinenumber;};
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 90 ".\\semanticAnalysis.l"
;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 91 ".\\semanticAnalysis.l"
{return *yytext;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 92 ".\\semanticAnalysis.l"
ECHO;
	YY_BREAK
#line 1293 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 304 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 304 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 303);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 92 ".\\semanticAnalysis.l"


int yywrap(){
    return 1;
}
